Repository bitcoin-s/bitcoin-s, pull requests merged in 2019-06, with the labels that each got.

#487 Publish website
  .travis.yml
  build.sbt
  docs/contributing-website.md
  docs/getting-started.md
  docs/rpc/bitcoind.md
  try-bitcoin-s.sh
  website/siteConfig.js
Labels: documentation

#491 Docs: Fix missing Scaladocs
  .travis.yml
Labels: documentation

#493 Make TestAsyncUtil serializable
  testkit/src/main/scala/org/bitcoins/testkit/async/TestAsyncUtil.scala
Labels: tests

#494 Multi module configuration
  build.sbt
  chain-test/src/test/scala/org/bitcoins/chain/pow/BitcoinPowTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/validation/TipValidationTest.scala
  chain/src/main/resources/chain.conf
  chain/src/main/scala/org/bitcoins/chain/api/ChainApi.scala
  chain/src/main/scala/org/bitcoins/chain/blockchain/Blockchain.scala
  chain/src/main/scala/org/bitcoins/chain/config/ChainAppConfig.scala
  chain/src/main/scala/org/bitcoins/chain/db/ChainDbManagement.scala
  chain/src/main/scala/org/bitcoins/chain/models/BlockHeaderDAO.scala
  db-commons/src/main/resources/db.conf
  db-commons/src/main/scala/org/bitcoins/db/AppConfig.scala
  db-commons/src/main/scala/org/bitcoins/db/CRUD.scala
  db-commons/src/main/scala/org/bitcoins/db/DbManagement.scala
  node-test/src/test/scala/org/bitcoins/node/networking/ClientTest.scala
  node-test/src/test/scala/org/bitcoins/node/util/BitcoinSpvNodeUtilTest.scala
  node/src/main/resources/node.conf
  node/src/main/scala/org/bitcoins/node/Main.scala
  node/src/main/scala/org/bitcoins/node/SpvNode.scala
  node/src/main/scala/org/bitcoins/node/config/NodeAppConfig.scala
  node/src/main/scala/org/bitcoins/node/constant/Constants.scala
  node/src/main/scala/org/bitcoins/node/models/PeerDAO.scala
  node/src/main/scala/org/bitcoins/node/networking/BlockActor.scala
  node/src/main/scala/org/bitcoins/node/networking/Client.scala
  node/src/main/scala/org/bitcoins/node/networking/PaymentActor.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/PeerMessageReceiver.scala
  project/Deps.scala
  testkit/src/main/resources/application.conf
  testkit/src/main/scala/org/bitcoins/testkit/BitcoinSAppConfig.scala
  testkit/src/main/scala/org/bitcoins/testkit/chain/ChainUnitTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/node/NodeTestUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/node/NodeUnitTest.scala
  testkit/src/test/scala/org/bitcoins/testkit/db/AppConfigTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletStorageTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/fixtures/AccountDAOFixture.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/fixtures/AddressDAOFixture.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/fixtures/DAOFixture.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/fixtures/UtxoDAOFixture.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/util/BitcoinSWalletTest.scala
  wallet/src/main/resources/wallet.conf
  wallet/src/main/scala/org/bitcoins/wallet/HDUtil.scala
  wallet/src/main/scala/org/bitcoins/wallet/LockedWallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/WalletStorage.scala
  wallet/src/main/scala/org/bitcoins/wallet/api/CreateWalletApi.scala
  wallet/src/main/scala/org/bitcoins/wallet/api/WalletApi.scala
  wallet/src/main/scala/org/bitcoins/wallet/config/WalletAppConfig.scala
  wallet/src/main/scala/org/bitcoins/wallet/models/AccountDAO.scala
  wallet/src/main/scala/org/bitcoins/wallet/models/AddressDAO.scala
  wallet/src/main/scala/org/bitcoins/wallet/models/UTXOSpendingInfoDAO.scala
Labels: chain, database, node, wallet

#498 Add debug prints to bitcoindCall when not on mainnet
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/Client.scala
Labels: bitcoind-rpc

#497 Legacy addresses
  chain/src/main/scala/org/bitcoins/chain/config/ChainAppConfig.scala
  db-commons/src/main/resources/reference.conf
  db-commons/src/main/scala/org/bitcoins/db/AppConfig.scala
  node/src/main/scala/org/bitcoins/node/config/NodeAppConfig.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/LegacyWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/SegwitWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletAppConfigTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletUnitTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/models/UTXOSpendingInfoDAOTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/util/BitcoinSWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/util/WalletTestUtil.scala
  wallet/src/main/scala/org/bitcoins/wallet/LockedWallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/config/WalletAppConfig.scala
  wallet/src/main/scala/org/bitcoins/wallet/models/AccountTable.scala
  wallet/src/main/scala/org/bitcoins/wallet/models/AddressTable.scala
  wallet/src/main/scala/org/bitcoins/wallet/models/UTXOSpendingInfoTable.scala
Labels: wallet

#502 Add Scaladoc title and version number
  .travis.yml
  build.sbt
Labels: documentation

#510 Docs: removes blog from website
  docker-compose.yml
  website/README.md
  website/blog/2019-05-9-bitcoin-s-website-release.md
  website/core/Footer.js
  website/i18n/en.json
  website/siteConfig.js
Labels: documentation

#509 Move Logback config into test resources
  build.sbt
  core/src/test/resources/common-logback.xml
  core/src/test/resources/logback.xml
Labels: tests

#506 Bump P2P + crypto test coverage
  core-test/README.md
  core-test/src/test/scala/org/bitcoins/core/crypto/ECPrivateKeySpec.scala
  core-test/src/test/scala/org/bitcoins/core/crypto/ECPrivateKeyTest.scala
  core-test/src/test/scala/org/bitcoins/core/crypto/ECPublicKeyTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/AddrMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/BlockMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/FeeFilterMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/FilterAddMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/FilterLoadMessageSpec.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/FilterLoadMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/GetBlocksMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/GetDataMessageSpec.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/GetDataMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/GetHeadersMessageSpec.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/GetHeadersMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/HeadersMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/InventoryMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/InventoryTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/MerkleBlockMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/NetworkHeaderTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/NetworkIpAddressTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/NetworkPayloadTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/NotFoundMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/PingMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/PongMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/RejectMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/TransactionMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/VersionMessageSpec.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/VersionMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/serializers/p2p/headers/RawNetworkHeaderSerializerTest.scala
  core-test/src/test/scala/org/bitcoins/core/serializers/p2p/messages/RawNetworkIpAddressSerializerTest.scala
  core/src/main/scala/org/bitcoins/core/config/NetworkParameters.scala
  core/src/main/scala/org/bitcoins/core/p2p/NetworkHeader.scala
  core/src/main/scala/org/bitcoins/core/p2p/NetworkIpAddress.scala
  core/src/main/scala/org/bitcoins/core/p2p/NetworkPayload.scala
  core/src/main/scala/org/bitcoins/core/p2p/ProtocolVersion.scala
  core/src/main/scala/org/bitcoins/core/p2p/serializers/messages/RawNetworkIpAddressSerializer.scala
  core/src/main/scala/org/bitcoins/core/p2p/serializers/messages/RawVersionMessageSerializer.scala
  core/src/main/scala/org/bitcoins/core/serializers/p2p/RawNetworkIpAddressSerializer.scala
  core/src/main/scala/org/bitcoins/core/serializers/p2p/headers/RawNetworkHeaderSerializer.scala
  core/src/main/scala/org/bitcoins/core/serializers/p2p/messages/RawAddrMessageSerializer.scala
  core/src/main/scala/org/bitcoins/core/serializers/p2p/messages/RawFeeFilterMessageSerializer.scala
  core/src/main/scala/org/bitcoins/core/wallet/fee/FeeUnit.scala
  docs/contributing.md
  testkit/src/main/scala/org/bitcoins/testkit/core/gen/CurrencyUnitGenerator.scala
  testkit/src/main/scala/org/bitcoins/testkit/core/gen/p2p/ControlMessageGenerator.scala
  testkit/src/main/scala/org/bitcoins/testkit/core/gen/p2p/DataMessageGenerator.scala
  testkit/src/main/scala/org/bitcoins/testkit/core/gen/p2p/P2PGenerator.scala
  testkit/src/main/scala/org/bitcoins/testkit/util/BitcoinSUnitTest.scala
Labels: core, documentation, tests

#511 Website guides on HD key and address generation
  core-test/src/test/scala/org/bitcoins/core/protocol/transaction/TransactionSpec.scala
  core-test/src/test/scala/org/bitcoins/core/protocol/transaction/TransactionTest.scala
  docs/core/addresses.md
  docs/core/core-intro.md
  docs/core/hd-keys.md
  docs/getting-started.md
  docs/rpc/rpc-clients-intro.md
  website/sidebars.json
Labels: documentation, tests

#501 Generate bloom filters from wallet
  core-test/src/test/scala/org/bitcoins/core/bloom/BloomFilterSpec.scala
  core-test/src/test/scala/org/bitcoins/core/bloom/BloomFilterTest.scala
  core-test/src/test/scala/org/bitcoins/core/hd/HDPathTest.scala
  core/src/main/scala/org/bitcoins/core/bloom/BloomFilter.scala
  core/src/main/scala/org/bitcoins/core/hd/HDPath.scala
  core/src/main/scala/org/bitcoins/core/util/FutureUtil.scala
  db-commons/src/main/resources/reference.conf
  db-commons/src/main/scala/org/bitcoins/db/CRUD.scala
  db-commons/src/main/scala/org/bitcoins/db/SlickUtil.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletUnitTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/LockedWallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/api/AddressInfo.scala
  wallet/src/main/scala/org/bitcoins/wallet/api/WalletApi.scala
  wallet/src/main/scala/org/bitcoins/wallet/config/WalletAppConfig.scala
  wallet/src/main/scala/org/bitcoins/wallet/models/AccountDAO.scala
  wallet/src/main/scala/org/bitcoins/wallet/models/AddressDAO.scala
Labels: core, wallet

#508 Bump various dependencies versions for our libraries
  project/Deps.scala
Labels: enhancement

#518 Fix issue where bloop didn't pick up test resources
  build.sbt
Labels: tests

#517 Default to file based databases in tests
  chain-test/src/test/scala/org/bitcoins/chain/blockchain/ChainHandlerTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/pow/BitcoinPowTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/validation/TipValidationTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/BitcoinSAppConfig.scala
Labels: database, tests

#519 [Tests] Kill all bitcoind instances after running
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/P2PRpcTest.scala
  node-test/src/test/scala/org/bitcoins/node/networking/ClientTest.scala
Labels: bitcoind-rpc, node, tests

#481 BIP 158 Golomb-Rice Coded Sets and block filters
  core-test/src/test/resources/testnet-19.json
  core-test/src/test/scala/org/bitcoins/core/gcs/BlockFilterTest.scala
  core-test/src/test/scala/org/bitcoins/core/gcs/GCSTest.scala
  core-test/src/test/scala/org/bitcoins/core/gcs/GolombFilterTest.scala
  core-test/src/test/scala/org/bitcoins/core/util/BitcoinScriptUtilTest.scala
  core/src/main/scala/org/bitcoins/core/gcs/GCS.scala
  core/src/main/scala/org/bitcoins/core/gcs/GolombFilter.scala
  core/src/main/scala/org/bitcoins/core/gcs/TempUtxoProvider.scala
  core/src/main/scala/org/bitcoins/core/protocol/script/ScriptPubKey.scala
  core/src/main/scala/org/bitcoins/core/util/BitcoinScriptUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/core/gen/NumberGenerator.scala
Labels: core

#537 Attempt to sync with sendheaders
  node-test/src/test/scala/org/bitcoins/node/SpvNodeTest.scala
  node/src/main/scala/org/bitcoins/node/networking/Client.scala
  testkit/src/main/scala/org/bitcoins/testkit/node/NodeUnitTest.scala
Labels: node

#541 Versioned website
  website/pages/en/versions.js
  website/versioned_docs/version-0.1.0/contributing-website.md
  website/versioned_docs/version-0.1.0/contributing.md
  website/versioned_docs/version-0.1.0/core/addresses.md
  website/versioned_docs/version-0.1.0/core/core-intro.md
  website/versioned_docs/version-0.1.0/core/hd-keys.md
  website/versioned_docs/version-0.1.0/core/txbuilder.md
  website/versioned_docs/version-0.1.0/getting-started.md
  website/versioned_docs/version-0.1.0/rpc/bitcoind.md
  website/versioned_docs/version-0.1.0/rpc/eclair.md
  website/versioned_docs/version-0.1.0/rpc/rpc-clients-intro.md
  website/versioned_docs/version-0.1.0/security.md
  website/versioned_sidebars/version-0.1.0-sidebars.json
  website/versions.json
Labels: documentation

#542 Docs: Add Algolia search to website
  website/siteConfig.js
Labels: documentation

#543 Add CNAME to website config
  website/siteConfig.js
Labels: documentation

#545 Add GA tag
  website/siteConfig.js
  website/static/js/google-analytics.js
Labels: documentation

#516 Generate test vectors from Trezor
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/serializers/JsonSerializers.scala
  wallet-test/src/test/resources/trezor-addresses.json
  wallet-test/src/test/scala/org/bitcoins/wallet/TrezorAddressTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/util/GetAddresses.scala
  wallet/src/main/scala/org/bitcoins/wallet/LockedWallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/api/WalletApi.scala
Labels: tests, wallet

#547 SipHashKey
  core-test/src/test/scala/org/bitcoins/core/gcs/GCSTest.scala
  core-test/src/test/scala/org/bitcoins/core/gcs/GolombFilterTest.scala
  core/src/main/scala/org/bitcoins/core/crypto/ECKey.scala
  core/src/main/scala/org/bitcoins/core/gcs/GCS.scala
  core/src/main/scala/org/bitcoins/core/gcs/GolombFilter.scala
  core/src/main/scala/org/bitcoins/core/gcs/SipHashKey.scala
  core/src/main/scala/org/bitcoins/core/hd/package.scala
  core/src/main/scala/org/bitcoins/core/protocol/blockchain/Block.scala
  core/src/main/scala/org/bitcoins/core/protocol/blockchain/ChainParams.scala
  core/src/main/scala/org/bitcoins/core/serializers/RawBitcoinSerializerHelper.scala
  core/src/main/scala/org/bitcoins/core/serializers/script/ScriptParser.scala
  core/src/test/resources/common-logback.xml
  core/src/test/resources/logback.xml
Labels: core

#431 Basic Coin Selection
  core-test/src/test/scala/org/bitcoins/core/wallet/builder/BitcoinTxBuilderTest.scala
  core-test/src/test/scala/org/bitcoins/core/wallet/builder/TxBuilderTest.scala
  core/src/main/scala/org/bitcoins/core/wallet/builder/TxBuilder.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/api/CoinSelectorTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/api/CoinSelector.scala
Labels: wallet

#546 Use key based encryption in AesCrypt
  build.sbt
  core-test/src/test/scala/org/bitcoins/core/crypto/AesCryptTest.scala
  core/src/main/scala/org/bitcoins/core/crypto/AesCrypt.scala
  core/src/main/scala/org/bitcoins/core/crypto/MnemonicCode.scala
  db-commons/src/main/scala/org/bitcoins/db/DbCommonsColumnMappers.scala
  testkit/src/main/scala/org/bitcoins/testkit/core/gen/CryptoGenerators.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/EncryptedMnemonicTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletStorageTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletUnitTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/EncryptedMnemonic.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/WalletStorage.scala
Labels: core, wallet

#553 implement Ordered[T] instead of creating custom methods
  core/src/main/scala/org/bitcoins/core/currency/CurrencyUnits.scala
  core/src/main/scala/org/bitcoins/core/number/NumberType.scala
  core/src/main/scala/org/bitcoins/core/protocol/ln/currency/LnCurrencyUnit.scala
  core/src/main/scala/org/bitcoins/core/protocol/ln/currency/MilliSatoshis.scala
  core/src/main/scala/org/bitcoins/core/script/constant/Constants.scala
Labels: core

#556 Add Bitcoin-S logo to git repo
  website/static/img/bitcoin-s-dark-logo.png
Labels: documentation
