Repository bitcoin-s/bitcoin-s, pull requests merged in 2019-09, with the labels that each got.

#728 Deprecate generate
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/BitcoindInstanceTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/BlockchainRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/MempoolRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/MiningRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/NodeRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/P2PRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/RawTransactionRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/WalletRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/v16/BitcoindV16RpcClientTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/v17/BitcoindV17RpcClientTest.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/MiningRpc.scala
  chain-test/src/test/scala/org/bitcoins/chain/blockchain/BitcoindChainHandlerViaZmqTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/blockchain/sync/ChainSyncTest.scala
  eclair-rpc-test/src/test/scala/org/bitcoins/eclair/rpc/EclairRpcClientTest.scala
  eclair-rpc-test/src/test/scala/org/bitcoins/eclair/rpc/EclairRpcTestUtilTest.scala
  node-test/src/test/scala/org/bitcoins/node/SpvNodeTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/eclair/rpc/EclairRpcTestUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/rpc/BitcoindRpcTestUtil.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletIntegrationTest.scala
Labels: bitcoind-rpc, eclair-rpc

#726 Add rudimentary docs for node, chain and wallet
  docs/applications/chain.md
  docs/applications/node.md
  docs/applications/wallet.md
  website/sidebars.json
Labels: documentation

#737 Add receiver param to BitcoindRpcTestUtil.fundBlockChainTransaction()
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/RawTransactionRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/WalletRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/v16/BitcoindV16RpcClientTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/v17/BitcoindV17RpcClientTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/v17/PsbtRpcTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/rpc/BitcoindRpcTestUtil.scala
Labels: bitcoind-rpc, teskit

#743 bump scalac version to 2.12.10
  .travis.yml
  inThisBuild.sbt
Labels: build

#755 Fix bug where we were sending messages before we were fully initialized
  node/src/main/scala/org/bitcoins/node/networking/peer/PeerMessageSender.scala
Labels: node

#757 Remove hard coded log level in test app config
  db-commons/src/main/resources/reference.conf
  testkit/src/main/scala/org/bitcoins/testkit/BitcoinSTestAppConfig.scala
Labels: logging

#764 Add akka logging documentation to our contributing.md
  app/server/src/main/resources/application.conf
  docs/contributing.md
  node/src/main/resources/application.conf
  node/src/main/scala/org/bitcoins/node/networking/P2PClient.scala
  testkit/src/main/resources/akka.conf
Labels: documentation, logging

#765 2019 09 27 logging refactor pt2
  app/server/src/main/resources/reference.conf
  docs/contributing.md
  eclair-rpc-test/src/test/scala/org/bitcoins/eclair/rpc/EclairRpcClientTest.scala
  eclair-rpc-test/src/test/scala/org/bitcoins/eclair/rpc/EclairRpcTestUtilTest.scala
  node/src/main/scala/org/bitcoins/node/networking/P2PClient.scala
  testkit/src/main/resources/akka.conf
  testkit/src/main/resources/reference.conf
  testkit/src/main/scala/org/bitcoins/testkit/rpc/BitcoindRpcTestUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/util/BitcoindRpcTest.scala
Labels: logging

#767 2019 09 28 common test trait
  .travis.yml
  binaries/scalafmt
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/TestRpcUtilTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/config/ChainAppConfigTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/pow/BitcoinPowTest.scala
  core-test/src/test/scala/org/bitcoins/core/gcs/GCSTest.scala
  eclair-rpc-test/src/test/scala/org/bitcoins/eclair/rpc/EclairRpcClientTest.scala
  eclair-rpc-test/src/test/scala/org/bitcoins/eclair/rpc/EclairRpcTestUtilTest.scala
  node-test/src/test/scala/org/bitcoins/node/networking/P2PClientTest.scala
  node-test/src/test/scala/org/bitcoins/node/networking/peer/PeerMessageHandlerTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/chain/ChainUnitTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/fixtures/BitcoinSFixture.scala
  testkit/src/main/scala/org/bitcoins/testkit/fixtures/NodeDAOFixture.scala
  testkit/src/main/scala/org/bitcoins/testkit/node/NodeUnitTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/util/BitcoinSAsyncTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/util/BitcoinSUnitTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/util/BitcoindRpcTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/BitcoinSWalletTest.scala
Labels: teskit, tests
