Repository bitcoin-s/bitcoin-s, pull requests merged in 2022-11, with the labels that each got.

#4868 Add test for another tx that broke lnd/btcd
  core-test/.jvm/src/test/resources/73be398c4bdc43709db7398106609eea2a7841aaf3a4fa2000dc18184faa2a7e.txt
  core-test/.jvm/src/test/scala/org/bitcoins/core/protocol/blockchain/BlockTest.scala
Labels: core, tests

#4869 Handle failed getting version of bitcoind
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/config/BitcoindInstance.scala
Labels: bug, bitcoind-rpc

#4870 Remove legacy GUI, this fixes CI merges to master
  .github/workflows/javafx.yml
  app/bundle/bundle.sbt
  app/bundle/src/main/resources/application.conf
  app/bundle/src/main/scala/org/bitcoins/bundle/gui/BitcoindConfigPane.scala
  app/bundle/src/main/scala/org/bitcoins/bundle/gui/BundleGUI.scala
  app/bundle/src/main/scala/org/bitcoins/bundle/gui/LandingPane.scala
  app/bundle/src/main/scala/org/bitcoins/bundle/gui/LandingPaneModel.scala
  app/bundle/src/main/scala/org/bitcoins/bundle/gui/NeutrinoConfigPane.scala
  app/bundle/src/main/scala/org/bitcoins/bundle/util/BitcoinSAppJFX3.scala
  app/gui/gui.sbt
  app/gui/src/main/resources/icons/bitcoin-s-regtest.png
  app/gui/src/main/resources/icons/bitcoin-s-signet.png
  app/gui/src/main/resources/icons/bitcoin-s-testnet.png
  app/gui/src/main/resources/icons/bitcoin-s.icns
  app/gui/src/main/resources/icons/bitcoin-s.png
  app/gui/src/main/resources/icons/copy-white.png
  app/gui/src/main/resources/icons/green-check.png
  app/gui/src/main/resources/icons/red-x.png
  app/gui/src/main/resources/themes/dark-theme.css
  app/gui/src/main/scala/org/bitcoins/gui/AppMenuBar.scala
  app/gui/src/main/scala/org/bitcoins/gui/ContractGUI.scala
  app/gui/src/main/scala/org/bitcoins/gui/ContractGUIModel.scala
  app/gui/src/main/scala/org/bitcoins/gui/GUI.scala
  app/gui/src/main/scala/org/bitcoins/gui/GlobalData.scala
  app/gui/src/main/scala/org/bitcoins/gui/TaskRunner.scala
  app/gui/src/main/scala/org/bitcoins/gui/WalletGUI.scala
  app/gui/src/main/scala/org/bitcoins/gui/WalletGUIModel.scala
  app/gui/src/main/scala/org/bitcoins/gui/contract/GlobalContractData.scala
  app/gui/src/main/scala/org/bitcoins/gui/dialog/AboutDialog.scala
  app/gui/src/main/scala/org/bitcoins/gui/dialog/DebugDialog.scala
  app/gui/src/main/scala/org/bitcoins/gui/dialog/FundingTransactionDialog.scala
  app/gui/src/main/scala/org/bitcoins/gui/dialog/GetNewAddressDialog.scala
  app/gui/src/main/scala/org/bitcoins/gui/dialog/SendDialog.scala
  app/gui/src/main/scala/org/bitcoins/gui/dialog/TransactionSentDialog.scala
  app/gui/src/main/scala/org/bitcoins/gui/dlc/DLCPane.scala
  app/gui/src/main/scala/org/bitcoins/gui/dlc/DLCPaneModel.scala
  app/gui/src/main/scala/org/bitcoins/gui/dlc/DLCPlotUtil.scala
  app/gui/src/main/scala/org/bitcoins/gui/dlc/DLCTableView.scala
  app/gui/src/main/scala/org/bitcoins/gui/dlc/GlobalDLCData.scala
  app/gui/src/main/scala/org/bitcoins/gui/dlc/dialog/AcceptOfferDialog.scala
  app/gui/src/main/scala/org/bitcoins/gui/dlc/dialog/BroadcastDLCDialog.scala
  app/gui/src/main/scala/org/bitcoins/gui/dlc/dialog/CliCommandProducer.scala
  app/gui/src/main/scala/org/bitcoins/gui/dlc/dialog/CreateDLCOfferDialog.scala
  app/gui/src/main/scala/org/bitcoins/gui/dlc/dialog/DLCDialog.scala
  app/gui/src/main/scala/org/bitcoins/gui/dlc/dialog/DLCDialogContainer.scala
  app/gui/src/main/scala/org/bitcoins/gui/dlc/dialog/ExecuteDLCDialog.scala
  app/gui/src/main/scala/org/bitcoins/gui/dlc/dialog/RefundDLCDialog.scala
  app/gui/src/main/scala/org/bitcoins/gui/dlc/dialog/SignDLCDialog.scala
  app/gui/src/main/scala/org/bitcoins/gui/dlc/dialog/ViewDLCDialog.scala
  app/gui/src/main/scala/org/bitcoins/gui/settings/SettingsPane.scala
  app/gui/src/main/scala/org/bitcoins/gui/settings/Themes.scala
  app/gui/src/main/scala/org/bitcoins/gui/util/GUIUtil.scala
  build.sbt
Labels: build, gui, bundle

#4464 Upgrade scalajs to 1.10.1
  .github/workflows/Linux_2.13_KeyManager_Wallet_DLC_Tests.yml
  .github/workflows/Linux_2.13_Node_Tests.yml
  core-test/src/test/scala/org/bitcoins/core/psbt/PSBTSerializerTest.scala
  project/plugins.sbt
Labels: dependencies, scalajs

#4871 Upgrade scalajs deps now that we have scalajs 1.11.0
  project/Deps.scala
Labels: dependencies, scalajs

#4874 Add OrderedTLVPoints as this is an invariant in the codebase
  core-test/.jvm/src/test/scala/org/bitcoins/core/dlc/testgen/DLCParsingTestVector.scala
  core/src/main/scala/org/bitcoins/core/package.scala
  core/src/main/scala/org/bitcoins/core/protocol/dlc/models/DLCPayoutCurve.scala
  core/src/main/scala/org/bitcoins/core/protocol/tlv/TLV.scala
  core/src/main/scala/org/bitcoins/core/util/sorted/OrderedTLVPoints.scala
Labels: enhancement, core

#4875 Add `OrderedDLCPayoutCurvePieces`
  core/src/main/scala/org/bitcoins/core/package.scala
  core/src/main/scala/org/bitcoins/core/protocol/dlc/models/DLCPayoutCurve.scala
  core/src/main/scala/org/bitcoins/core/util/sorted/OrderedDLCPayoutCurvePieces.scala
Labels: core, refactor

#4877 Update scalapb-runtime to 0.11.12
  project/Deps.scala
Labels: dependencies

#4876 Update junixsocket-core to 2.6.1
  project/Deps.scala
Labels: dependencies

#4879 Fix alpha dlc categorization, delete dlcs that are alpha again
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCAppConfig.scala
Labels: dlc, dlc-wallet

#4880 Update sqlite-jdbc to 3.39.4.0
  project/Deps.scala
Labels: dependencies

#4882 Bump lnd to v0.15.4
  lnd-rpc/lnd-rpc.sbt
  lnd-rpc/src/main/scala/org/bitcoins/lnd/rpc/LndRpcClient.scala
Labels: lnd-rpc

#4881 Support bip32 paths with 'h' instead of an apostrophe
  core-test/src/test/scala/org/bitcoins/core/crypto/bip32/BIP32PathTest.scala
  core/src/main/scala/org/bitcoins/core/hd/BIP32Path.scala
Labels: core

#4887 Update sbt-scalajs-bundler to 0.21.1
  project/plugins.sbt
Labels: dependencies

#4883 2022 11 11 sbt 1.8.0
  .github/workflows/Linux_2.13_App_Chain_Core_Tests.yml
  .github/workflows/Linux_2.13_KeyManager_Wallet_DLC_Tests.yml
  .github/workflows/Linux_2.13_Node_Tests.yml
  .github/workflows/Linux_2.13_RPC_Tests.yml
  .github/workflows/Mac_2.13_RPC_Tests.yml
  .github/workflows/Mac_2.13_Wallet_Node_DLC_Tests.yml
  .github/workflows/PostgresTests.yml
  .github/workflows/Secp_Disabled_Tests.yml
  .github/workflows/TorTests.yml
  .github/workflows/Windows.yml
  .github/workflows/docker-publish.yml
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/MiningRpcTest.scala
  chain/src/main/scala/org/bitcoins/chain/blockchain/BlockchainUpdate.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala
  esplora-test/src/test/scala/org/bitcoins/esplora/EsploraClientTest.scala
  inThisBuild.sbt
  project/build.properties
  project/plugins.sbt
Labels: build

#4888 Update janino to 3.1.9
  project/Deps.scala
Labels: dependencies

#4891 Update sqlite-jdbc to 3.39.4.1
  project/Deps.scala
Labels: dependencies

#4893 Update metrics-core, metrics-healthchecks, ... to 4.2.13
  project/Deps.scala
Labels: dependencies

#4890 Update slf4j-api to 2.0.4
  project/Deps.scala
Labels: dependencies

#4895 Update sqlite-jdbc to 3.40.0.0
  project/Deps.scala
Labels: dependencies

#4896 Improve error logging on server
  app/server-routes/src/main/scala/org/bitcoins/server/routes/Server.scala
Labels: logging, app server, oracleServer

#4897 Delay querying for peers for 30 minutes
  node/src/main/scala/org/bitcoins/node/PeerFinder.scala
Labels: node

#4899 Update sbt-scalajs, scalajs-compiler, ... to 1.12.0
  project/plugins.sbt
Labels: dependencies

#4901 Update slf4j-api to 2.0.5
  project/Deps.scala
Labels: dependencies

#4898 Update postgresql to 42.5.1
  project/Deps.scala
Labels: dependencies

#4900 Fix isLocalhost for 127.0.0.1
  core/src/main/scala/org/bitcoins/core/util/NetworkUtil.scala
Labels: bug, core

#4903 Update scala-java-time to 2.5.0
  project/Deps.scala
Labels: dependencies
