Repository bitcoin-s/bitcoin-s, pull requests merged in 2023-09, with the labels that each got.

#5217 2023 08 30 refactor `ConsoleCli`
  app/cli/src/main/resources/logback.xml
  app/cli/src/main/scala/org/bitcoins/cli/ConsoleCli.scala
  project/CommonSettings.scala
  project/Deps.scala
Labels: refactor, cli

#5223 Optimize `bestFilterHeaderHeightQuery`
  chain/src/main/scala/org/bitcoins/chain/models/CompactFilterHeaderDAO.scala
Labels: chain, optimization

#5224 Reduce `NodeCallbackStreamManager` to 32 to reduce chance of `OOM` errors
  node/src/main/scala/org/bitcoins/node/callback/NodeCallbackStreamManager.scala
Labels: bug, node, initial-block-download

#5225 Fix bug were we weren't consistently calculating the correct compact filter start height for sync
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeTest.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
Labels: bug, node

#5229 Reduce NodeCallbackStreamManager from `32` -> `16`
  node/src/main/scala/org/bitcoins/node/callback/NodeCallbackStreamManager.scala
Labels: node

#5230 reduce default `bitcoin-s.chain.neutrino.filter-batch-size` to `250`
  db-commons/src/main/resources/reference.conf
Labels: node, config

#5232 Update scalatest to 3.2.17
  project/Deps.scala
Labels: dependencies

#5233 Update sbt-scoverage to 2.0.9
  project/plugins.sbt
Labels: dependencies

#5234 Update junixsocket-core to 2.7.1
  project/Deps.scala
Labels: dependencies

#5235 Update scala-library to 2.13.12
  app/scripts/src/main/scala/org/bitcoins/scripts/ScanBitcoind.scala
  app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala
  app/server/src/main/scala/org/bitcoins/server/BitcoindRpcBackendUtil.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/TestRpcUtilTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/BlockchainRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/P2PRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/PreciousBlockRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/UTXORpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/v21/BitcoindV21RpcClientTest.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/BitcoindRpcClient.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/BlockchainRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/v21/BitcoindV21RpcClient.scala
  chain-test/src/test/scala/org/bitcoins/chain/blockchain/BitcoindChainHandlerViaZmqTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/blockchain/sync/ChainSyncTest.scala
  dlc-wallet-test/src/test/scala/org/bitcoins/dlc/integration/DLCClientIntegrationTest.scala
  esplora/src/main/scala/org/bitcoins/esplora/EsploraClient.scala
  inThisBuild.sbt
  lnd-rpc-test/src/test/scala/org/bitcoins/lnd/rpc/LndRpcClientPairTest.scala
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeTest.scala
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeWithWalletTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/chain/ChainUnitTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/chain/SyncUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/clightning/CLightningRpcTestUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/eclair/rpc/EclairRpcTestUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/lnd/LndRpcTestUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/node/NodeTestUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/rpc/BitcoindRpcTestUtil.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/BitcoindBackendTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/ProcessBlockTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/UTXOLifeCycleTest.scala
Labels: dependencies

#5237 Update sbt to 1.9.6
  project/build.properties
Labels: dependencies

#5236 Update junixsocket-core to 2.7.2
  project/Deps.scala
Labels: dependencies

#5239 Update play-json to 2.10.1
  project/Deps.scala
Labels: dependencies

#5240 Adjust so that requery in the case were we have just 1 peer
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
Labels: bug, node, initial-block-download

#5241 Switch defaults to 12 hours for running `peerConnectionScheduler`
  db-commons/src/main/resources/reference.conf
  node/src/main/scala/org/bitcoins/node/PeerFinder.scala
  node/src/main/scala/org/bitcoins/node/config/NodeAppConfig.scala
Labels: node

#5243 Fix chain fixtures to use `ChainHandler` rather than always using `ChainHandlerCached`
  testkit/src/main/scala/org/bitcoins/testkit/chain/ChainUnitTest.scala
Labels: chain, testkit

#5244 Update metrics-core, metrics-healthchecks, ... to 4.2.20
  project/Deps.scala
Labels: dependencies

#5245 Update sbt-scalajs, scalajs-compiler, ... to 1.14.0
  project/plugins.sbt
Labels: dependencies

#5246 Update jeromq to 0.5.4
  project/Deps.scala
Labels: dependencies

#5247 2023 09 27 issue 5139
  chain-test/src/test/scala/org/bitcoins/chain/blockchain/ChainHandlerCachedTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/blockchain/ChainHandlerTest.scala
  chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala
  core/src/main/scala/org/bitcoins/core/api/chain/ChainApi.scala
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeTest.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
Labels: bug, chain, node

#5249 Move `NodeState` to `core`
  core/src/main/scala/org/bitcoins/core/api/node/NodeState.scala
  node-test/src/test/scala/org/bitcoins/node/networking/peer/DataMessageHandlerTest.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
  node/src/main/scala/org/bitcoins/node/util/PeerMessageSenderApi.scala
Labels: core, refactor
