Repository bitcoin-s/bitcoin-s, pull requests merged in 2023-10, with the labels that each got.

#5250 Move initialization of sync into PeerManager's queue
  node/src/main/scala/org/bitcoins/node/NeutrinoNode.scala
  node/src/main/scala/org/bitcoins/node/NodeStreamMessage.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
Labels: node, refactor

#5251 2023 09 29 waitingdisconnection nodestate
  core/src/main/scala/org/bitcoins/core/api/node/NodeState.scala
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeTest.scala
  node-test/src/test/scala/org/bitcoins/node/networking/peer/DataMessageHandlerTest.scala
  node/src/main/scala/org/bitcoins/node/NodeStreamMessage.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
  node/src/main/scala/org/bitcoins/node/util/PeerMessageSenderApi.scala
Labels: node, refactor

#5252 Update junixsocket-core to 2.8.1
  project/Deps.scala
Labels: dependencies

#5254 Fix bug where we were executing block ehader callbacks...
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
Labels: bug, node

#5253 Move `filterBatchCache` into `NodeState.FilterSync`
  core/src/main/scala/org/bitcoins/core/api/node/NodeState.scala
  node-test/src/test/scala/org/bitcoins/node/networking/peer/DataMessageHandlerTest.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
Labels: node, refactor

#5255 Change `PeerManager` to keep `NodeState` in `Sink.foldAsync()` rather than `DataMessageHandler`
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
Labels: node, refactor

#5256 2023 10 03 node refactors
  app/scripts/src/main/resources/logback.xml
  app/server/src/main/resources/logback.xml
  core/src/main/scala/org/bitcoins/core/api/node/PeerManagerApi.scala
  node-test/src/test/scala/org/bitcoins/node/networking/peer/DataMessageHandlerTest.scala
  node/src/main/scala/org/bitcoins/node/Node.scala
  node/src/main/scala/org/bitcoins/node/PeerData.scala
  node/src/main/scala/org/bitcoins/node/PeerFinder.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/ControlMessageHandler.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/PeerConnection.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/PeerMessageSender.scala
  node/src/main/scala/org/bitcoins/node/util/PeerMessageSenderApi.scala
Labels: node, refactor

#5257 Update sbt-mdoc to 2.3.8
  project/plugins.sbt
Labels: dependencies

#5259 Use `BitcoindRpcBackendUtil.buildBitcoindNodeApi()` in wallet test fixtures
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/util/BitcoindStreamUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/chain/SyncUtil.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/UtxoHandling.scala
Labels: wallet, testkit, refactor

#5261 Update metrics-core, metrics-healthchecks, ... to 4.2.21
  project/Deps.scala
Labels: dependencies

#5266 Update sbt-mdoc to 2.4.0
  project/plugins.sbt
Labels: dependencies

#5263 2023 10 16 Implement `WalletCallbackStreamManager,` `DLCWalletCallbackStreamManager`
  app/server-test/src/test/scala/org/bitcoins/server/WebsocketTests.scala
  app/server/src/main/scala/org/bitcoins/server/util/WebsocketUtil.scala
  dlc-wallet-test/src/test/scala/org/bitcoins/dlc/wallet/DLCWalletCallbackTest.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCAppConfig.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/callback/DLCWalletCallbackStreamManager.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/callback/DLCWalletCallbacks.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/internal/DLCTransactionProcessing.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/internal/IncomingDLCOffersHandling.scala
  docs/wallet/wallet-callbacks.md
  docs/wallet/wallet-rescan.md
  node/src/main/scala/org/bitcoins/node/callback/NodeCallbackStreamManager.scala
  testkit/src/main/scala/org/bitcoins/testkit/node/NodeTestWithCachedBitcoind.scala
  testkit/src/main/scala/org/bitcoins/testkit/node/NodeUnitTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/BitcoinSWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletCallbackTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/callback/OnBlockProcessed.scala
  wallet/src/main/scala/org/bitcoins/wallet/callback/OnFeeRateChanged.scala
  wallet/src/main/scala/org/bitcoins/wallet/callback/OnNewAddressGenerated.scala
  wallet/src/main/scala/org/bitcoins/wallet/callback/OnRescanComplete.scala
  wallet/src/main/scala/org/bitcoins/wallet/callback/OnReservedUtxos.scala
  wallet/src/main/scala/org/bitcoins/wallet/callback/OnTransactionBroadcast.scala
  wallet/src/main/scala/org/bitcoins/wallet/callback/OnTransactionProcessed.scala
  wallet/src/main/scala/org/bitcoins/wallet/callback/WalletCallbackStreamManager.scala
  wallet/src/main/scala/org/bitcoins/wallet/callback/WalletCallbacks.scala
  wallet/src/main/scala/org/bitcoins/wallet/config/WalletAppConfig.scala
Labels: enhancement, wallet, dlc-wallet

#5269 2023 10 19 recursive rescan state
  app/server-test/src/test/scala/org/bitcoins/server/RoutesSpec.scala
  app/server-test/src/test/scala/org/bitcoins/server/WebsocketTests.scala
  app/server/src/main/scala/org/bitcoins/server/DLCWalletLoaderApi.scala
  app/server/src/main/scala/org/bitcoins/server/WalletRoutes.scala
  core/src/main/scala/org/bitcoins/core/wallet/rescan/RescanState.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/RescanHandlingTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/RescanHandling.scala
Labels: bug, wallet, rescan

#5270 Update play-json to 2.10.2
  project/Deps.scala
Labels: dependencies

#5273 Update scodec-bits to 1.1.38
  project/Deps.scala
Labels: dependencies

#5271 Update sbt to 1.9.7
  project/build.properties
Labels: dependencies

#5276 Update junixsocket-core to 2.8.2
  project/Deps.scala
Labels: dependencies

#5277 Bump timeout for checking when peer is disconnected
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeTest.scala
Labels: tests

#5226 Update sbt-bloop to 1.5.11
  bitcoin-s-docs/docs.sbt
  project/plugins.sbt
Labels: dependencies

#5275 Update sbt-assembly to 2.1.4
  project/plugins.sbt
Labels: dependencies
