Repository bitcoin-s/bitcoin-s, pull requests merged in 2023-11, with the labels that each got.

#5279 Upgrade website dependencies
  website/yarn.lock
Labels: documentation

#5284 Upgrade to bitcoind `24.2`
  bitcoind-rpc/bitcoind-rpc.sbt
Labels: bitcoind-rpc

#5283 Update metrics-core, metrics-healthchecks, ... to 4.2.22
  project/Deps.scala
Labels: dependencies

#5282 Update play-json to 2.10.3
  project/Deps.scala
Labels: dependencies

#5285 Make `Gen[ECPrivateKey]` in scalacheck to use randomness from scalacheck to preserve reproducibility of test cases
  crypto-test/src/test/scala/org/bitcoins/crypto/CryptoGenerators.scala
  testkit-core/src/main/scala/org/bitcoins/testkitcore/gen/ScriptGenerators.scala
Labels: bug, testkit

#5287 Fix `NullPointerException` inside of `DLCServer`
  dlc-node/src/main/scala/org/bitcoins/dlc/node/DLCServer.scala
Labels: dlc-node

#5289 Update sbt-mdoc to 2.5.0
  project/plugins.sbt
Labels: dependencies

#5290 Reset `PeerConnection.connectionGraphOpt = None` when connection is disconnected
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeTest.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/PeerConnection.scala
Labels: bug, node

#5286 Reduce inactivity level to `DEBUG`
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
Labels: node

#5297 Update native-lib-loader to 2.5.0
  project/Deps.scala
Labels: dependencies

#5298 Update sbt-mdoc to 2.5.1
  project/plugins.sbt
Labels: dependencies

#5296 Update client3:core, ... to 3.9.1
  project/Deps.scala
Labels: dependencies

#5302 Update bcprov-jdk18on to 1.77
  project/Deps.scala
Labels: dependencies

#5300 Update junixsocket-core to 2.8.3
  project/Deps.scala
Labels: dependencies

#5303 2023 11 10 peermanager refactor
  core/src/main/scala/org/bitcoins/core/api/node/NodeState.scala
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeWithUncachedBitcoindTest.scala
  node/src/main/scala/org/bitcoins/node/NeutrinoNode.scala
  node/src/main/scala/org/bitcoins/node/Node.scala
  node/src/main/scala/org/bitcoins/node/PeerData.scala
  node/src/main/scala/org/bitcoins/node/PeerFinder.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/ControlMessageHandler.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/PeerConnection.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/PeerMessageSender.scala
  node/src/main/scala/org/bitcoins/node/util/PeerMessageSenderApi.scala
  testkit-core/.jvm/src/main/resources/logback-test.xml
Labels: node, refactor

#5308 Remove oracle explorer client
  .github/workflows/Linux_2.13_KeyManager_Wallet_DLC_Tests.yml
  build.sbt
  docs/oracle-explorer-client/oracle-explorer-client.md
  oracle-explorer-client/src/main/scala/org/bitcoins/explorer/client/SbExplorerClient.scala
  oracle-explorer-client/src/main/scala/org/bitcoins/explorer/model/CreateAnnouncementExplorer.scala
  oracle-explorer-client/src/main/scala/org/bitcoins/explorer/model/CreateAttestations.scala
  oracle-explorer-client/src/main/scala/org/bitcoins/explorer/model/Oracle.scala
  oracle-explorer-client/src/main/scala/org/bitcoins/explorer/model/SbAnnouncementEvent.scala
  oracle-explorer-client/src/main/scala/org/bitcoins/explorer/picklers/ExplorerPicklers.scala
  oracle-explorer-client/src/test/scala/org/bitcoins/explorer/client/SbExplorerClientTest.scala
  oracle-explorer-client/src/test/scala/org/bitcoins/explorer/env/ExplorerEnvTest.scala
  oracle-explorer-client/src/test/scala/org/bitcoins/explorer/model/SbOracleEventExplorerTest.scala
  project/Deps.scala
Labels: explorer-client

#5311 Replace inactivity logic with `Flow.idleTimeout`
  node/src/main/scala/org/bitcoins/node/NeutrinoNode.scala
  node/src/main/scala/org/bitcoins/node/PeerData.scala
  node/src/main/scala/org/bitcoins/node/PeerFinder.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/PeerConnection.scala
Labels: node, refactor
