Repository bitcoin-s/bitcoin-s, pull requests merged in 2023-03, with the labels that each got.

#5008 2023 02 27 Fix bug where duplicate filters caused node not to sync
  chain-test/src/test/scala/org/bitcoins/chain/blockchain/ChainHandlerTest.scala
  chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala
  chain/src/main/scala/org/bitcoins/chain/models/CompactFilterDAO.scala
  node-test/src/test/scala/org/bitcoins/node/networking/peer/DataMessageHandlerTest.scala
  node/src/main/scala/org/bitcoins/node/NeutrinoNode.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
Labels: bug, chain, node

#4999 Update metrics-core, metrics-healthchecks, ... to 4.2.17
  project/Deps.scala
Labels: dependencies

#5007 Update client3:core to 3.8.12
  project/Deps.scala
Labels: dependencies

#4994 Update Eclair RPC to v0.8.0
  app-commons/src/main/scala/org/bitcoins/commons/jsonmodels/eclair/EclairModels.scala
  app-commons/src/main/scala/org/bitcoins/commons/serializers/JsonReaders.scala
  core/src/main/scala/org/bitcoins/core/protocol/ln/channel/ChannelState.scala
  core/src/main/scala/org/bitcoins/core/protocol/ln/node/Feature.scala
  eclair-rpc-test/src/test/scala/org/bitcoins/eclair/rpc/EclairRpcClientTest.scala
  eclair-rpc/eclair-rpc.sbt
  eclair-rpc/src/main/scala/org/bitcoins/eclair/rpc/api/EclairApi.scala
  eclair-rpc/src/main/scala/org/bitcoins/eclair/rpc/client/EclairRpcClient.scala
Labels: enhancement, eclair-rpc

#5009 2023 03 03 rm `DataMessageHandler` filter params
  chain-test/src/test/scala/org/bitcoins/chain/blockchain/BlockchainTest.scala
  chain/src/main/scala/org/bitcoins/chain/blockchain/BaseBlockChain.scala
  chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala
  core/src/main/scala/org/bitcoins/core/p2p/NetworkPayload.scala
  node-test/src/test/scala/org/bitcoins/node/networking/peer/DataMessageHandlerTest.scala
  node/src/main/scala/org/bitcoins/node/NeutrinoNode.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
Labels: node, refactor

#5011 Generate blocks in two rpc calls
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeTest.scala
Labels: node, tests

#5016 Fix MilliSatoshis.toSatoshis for large values
  core-test/src/test/scala/org/bitcoins/core/protocol/ln/currency/MilliSatoshisTest.scala
  core/src/main/scala/org/bitcoins/core/protocol/ln/currency/MilliSatoshis.scala
Labels: bug, core

#5015 Update slf4j-api to 2.0.7
  project/Deps.scala
Labels: dependencies

#5014 Update postgresql to 42.6.0
  project/Deps.scala
Labels: dependencies

#5012 Update logback-classic to 1.4.6
  project/Deps.scala
Labels: dependencies

#5013 Update metrics-core, metrics-healthchecks, ... to 4.2.18
  project/Deps.scala
Labels: dependencies

#5010 Update client3:core to 3.8.13
  project/Deps.scala
Labels: dependencies

#5018 Try bumping timeout to 1 second to avoid false positives test failures
  app/server-test/src/test/scala/org/bitcoins/server/DLCWalletBitcoindBackendLoaderTest.scala
Labels: tests

#5021 Fix `empty.tail` exception occurring on chain block filter / filter headers callbacks
  app/server/src/main/scala/org/bitcoins/server/util/WebsocketUtil.scala
Labels: bug, app server

#5019 Update sqlite-jdbc to 3.41.0.1
  project/Deps.scala
Labels: dependencies

#5025 Bump clightning version to `v23.02.2`
  clightning-rpc/clightning-rpc.sbt
  clightning-rpc/src/main/scala/com/bitcoins/clightning/rpc/CLightningRpcClient.scala
  testkit/src/main/scala/org/bitcoins/testkit/clightning/CLightningRpcTestClient.scala
Labels: bug, clightning

#5024 2023 03 24 is tip stale
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/BitcoindRpcClient.scala
  chain-test/src/test/scala/org/bitcoins/chain/ChainCallbacksTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/blockchain/BlockchainTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/blockchain/ChainHandlerCachedTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/blockchain/ChainHandlerTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/blockchain/MainnetChainHandlerTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/models/BlockHeaderDAOTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/models/CompactFilterDAOTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/models/CompactFilterHeaderDAOTest.scala
  chain-test/src/test/scala/org/bitcoins/chain/pow/BitcoinPowTest.scala
  chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala
  chain/src/main/scala/org/bitcoins/chain/pow/Pow.scala
  core-test/src/test/scala/org/bitcoins/core/util/NetworkUtilTest.scala
  core/src/main/scala/org/bitcoins/core/api/chain/ChainApi.scala
  core/src/main/scala/org/bitcoins/core/api/chain/db/BlockHeaderDb.scala
  core/src/main/scala/org/bitcoins/core/protocol/blockchain/BlockHeader.scala
  core/src/main/scala/org/bitcoins/core/protocol/blockchain/ChainParams.scala
  core/src/main/scala/org/bitcoins/core/util/NetworkUtil.scala
  testkit-core/src/main/scala/org/bitcoins/testkitcore/chain/ChainTestUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/chain/ChainUnitTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/node/BaseNodeTest.scala
Labels: chain, core, bitcoind-rpc, refactor

#5027 Update sqlite-jdbc to 3.41.2.1
  project/Deps.scala
Labels: dependencies

#5026 Update waffle-jna to 3.3.0
  project/Deps.scala
Labels: dependencies

#5005 Lnd 0.16.0 rpc
  lnd-rpc/lnd-rpc.sbt
  lnd-rpc/src/main/protobuf/chainrpc/chainnotifier.proto
  lnd-rpc/src/main/protobuf/invoicesrpc/invoices.proto
  lnd-rpc/src/main/protobuf/lightning.proto
  lnd-rpc/src/main/protobuf/peersrpc/peers.proto
  lnd-rpc/src/main/protobuf/routerrpc/router.proto
  lnd-rpc/src/main/protobuf/signrpc/signer.proto
  lnd-rpc/src/main/protobuf/stateservice.proto
  lnd-rpc/src/main/protobuf/walletrpc/walletkit.proto
  lnd-rpc/src/main/protobuf/walletunlocker.proto
  lnd-rpc/src/main/scala/org/bitcoins/lnd/rpc/LndRpcClient.scala
  testkit/src/main/scala/org/bitcoins/testkit/lnd/LndRpcTestUtil.scala
Labels: lnd-rpc
