Repository bitcoin-s/bitcoin-s, pull requests merged in 2023-02, with the labels that each got.

#4970 Refactor to not throw an exception is node is already syncing
  testkit/src/main/scala/org/bitcoins/testkit/node/NodeUnitTest.scala
Labels: testkit, refactor

#4966 Add check we have more than 1 peer before we try to `syncFromNewPeer()`
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
  testkit-core/.jvm/src/main/resources/logback-test.xml
Labels: bug, node

#4971 Segregate handling of exceptions in fixtures
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeWithWalletTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/fixtures/BitcoinSFixture.scala
  testkit/src/main/scala/org/bitcoins/testkit/node/NodeTestUtil.scala
Labels: testkit, refactor

#4973 Refactor `NodeTestUtil.awaitBestHash()` to take a reference to `bitcoind`
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeTest.scala
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeWithUncachedBitcoindTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/node/NodeTestUtil.scala
Labels: testkit, refactor

#4974 Segregate `P2PClientTest` and `P2PClientActorTest`
  node-test/src/test/scala/org/bitcoins/node/BroadcastTransactionTest.scala
  node-test/src/test/scala/org/bitcoins/node/DisconnectedPeerTest.scala
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeTest.scala
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeWithUncachedBitcoindTest.scala
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeWithWalletTest.scala
  node-test/src/test/scala/org/bitcoins/node/NeutrinoUnsupportedPeerTest.scala
  node-test/src/test/scala/org/bitcoins/node/PeerManagerTest.scala
  node-test/src/test/scala/org/bitcoins/node/networking/P2PClientActorTest.scala
  node-test/src/test/scala/org/bitcoins/node/networking/P2PClientTest.scala
  node-test/src/test/scala/org/bitcoins/node/networking/ReConnectionTest.scala
  node-test/src/test/scala/org/bitcoins/node/networking/peer/DataMessageHandlerTest.scala
  node-test/src/test/scala/org/bitcoins/node/networking/peer/PeerMessageReceiverTest.scala
  node/src/main/scala/org/bitcoins/node/NeutrinoNode.scala
  testkit/src/main/scala/org/bitcoins/testkit/BitcoinSTestAppConfig.scala
  testkit/src/main/scala/org/bitcoins/testkit/fixtures/BitcoinSAppConfigFixture.scala
  testkit/src/main/scala/org/bitcoins/testkit/fixtures/DLCDAOFixture.scala
  testkit/src/main/scala/org/bitcoins/testkit/fixtures/NodeDAOFixture.scala
  testkit/src/main/scala/org/bitcoins/testkit/fixtures/WalletDAOFixture.scala
  testkit/src/main/scala/org/bitcoins/testkit/util/BitcoindRpcTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/BaseWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/TrezorAddressTest.scala
Labels: node, testkit, refactor

#4980 Update sbt-native-packager to 1.9.14
  project/plugins.sbt
Labels: dependencies

#4978 Update scalapb-runtime to 0.11.13
  project/Deps.scala
Labels: dependencies

#4977 Update client3:core to 3.8.11
  project/Deps.scala
Labels: dependencies

#4969 Update sqlite-jdbc to 3.40.1.0
  project/Deps.scala
Labels: dependencies

#4972 Update postgresql to 42.5.3
  project/Deps.scala
Labels: dependencies

#4983 Add rpc for `syncwithvalidationinterfacequeue`, use it in `NodeUnitTest.syncNeutrinoNode`
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/BlockchainRpc.scala
  testkit/src/main/scala/org/bitcoins/testkit/node/NodeUnitTest.scala
Labels: bug, bitcoind-rpc, testkit

#4917 2022 12 05 issue 4904
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/BitcoindRpcClient.scala
Labels: bug, node

#4981 Update junixsocket-core to 2.6.2
  project/Deps.scala
Labels: dependencies

#4963 Update sbt-scalajs, scalajs-compiler, ... to 1.13.0
  project/plugins.sbt
Labels: dependencies

#4951 Update jna to 5.13.0
  project/Deps.scala
Labels: dependencies

#4929 Update org.osgi.service.jdbc to 1.1.0
  project/Deps.scala
Labels: dependencies

#4986 Fix `UTXORpcTest` flakiness
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/UTXORpcTest.scala
Labels: bug, bitcoind-rpc

#4985 Bump timeout in `P2PClientActorTest`
  node-test/src/test/scala/org/bitcoins/node/networking/P2PClientActorTest.scala
Labels: node

#4979 Update scodec-bits to 1.1.35
  project/Deps.scala
Labels: dependencies

#4987 Call `syncwithvalidationinterfacequeue` inside of `{generatetoaddress,generateblock}`
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/MiningRpc.scala
Labels: bitcoind-rpc

#4988 Add nostr zaps params for lnurl
  lnurl/src/main/scala/org/bitcoins/lnurl/json/LnURLJsonModels.scala
Labels: lnurl

#4982 Update sbt-scoverage to 2.0.7
  project/plugins.sbt
Labels: dependencies

#4990 Update metrics-core, metrics-healthchecks, ... to 4.2.16
  project/Deps.scala
Labels: dependencies

#4989 Update sbt-native-packager to 1.9.15
  project/plugins.sbt
Labels: dependencies

#4991 Remove support for `v19` of bitcoind
  app-commons/src/main/scala/org/bitcoins/commons/jsonmodels/bitcoind/NetworkResult.scala
  app-commons/src/main/scala/org/bitcoins/commons/jsonmodels/bitcoind/WalletResult.scala
  app-commons/src/main/scala/org/bitcoins/commons/serializers/JsonSerializers.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/BitcoindVersionTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/BlockchainRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/MultiWalletRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/WalletRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/v19/BitcoindV19RpcClientTest.scala
  bitcoind-rpc/bitcoind-rpc.sbt
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/BitcoindRpcClient.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/BlockchainRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/MempoolRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/MultisigRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/P2PRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/PsbtRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/RawTransactionRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/TransactionRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/UtilRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/WalletRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/v18/V18AssortedRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/v19/BitcoindV19RpcClient.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/v20/V20MultisigRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/config/BitcoindInstance.scala
  docs/chain/chain-query-api.md
  docs/chain/filter-sync.md
  docs/core/txbuilder.md
  docs/node/node-api.md
  docs/node/node.md
  docs/testkit/testkit.md
  docs/wallet/wallet-callbacks.md
  docs/wallet/wallet-rescan.md
  docs/wallet/wallet-sync.md
  docs/wallet/wallet.md
  testkit/src/main/scala/org/bitcoins/testkit/chain/ChainUnitTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/node/NodeTestWithCachedBitcoind.scala
  testkit/src/main/scala/org/bitcoins/testkit/rpc/BitcoindFixtures.scala
  testkit/src/main/scala/org/bitcoins/testkit/rpc/BitcoindRpcTestUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/rpc/CachedBitcoind.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/BitcoinSWalletTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/BitcoinSWalletTestCachedBitcoind.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/WalletWithBitcoind.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/ProcessBlockTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/sync/WalletSyncTest.scala
Labels: bitcoind-rpc, refactor

#4992 Remove `v20` bitcoind support
  app-commons/src/main/scala/org/bitcoins/commons/jsonmodels/bitcoind/NetworkResult.scala
  app-commons/src/main/scala/org/bitcoins/commons/serializers/JsonSerializers.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/BitcoindVersionTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/UTXORpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/WalletRpcTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/v20/BitcoindV20RpcClientTest.scala
  bitcoind-rpc/bitcoind-rpc.sbt
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/BitcoindRpcClient.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/BlockchainRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/MempoolRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/MultisigRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/P2PRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/PsbtRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/RawTransactionRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/TransactionRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/UtilRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/WalletRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/v18/V18AssortedRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/v20/BitcoindV20RpcClient.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/v20/V20MultisigRpc.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/config/BitcoindInstance.scala
  testkit/src/main/scala/org/bitcoins/testkit/rpc/BitcoindFixtures.scala
  testkit/src/main/scala/org/bitcoins/testkit/rpc/BitcoindRpcTestUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/rpc/CachedBitcoind.scala
Labels: bitcoind-rpc

#4993 Update postgresql to 42.5.4
  project/Deps.scala
Labels: dependencies

#4995 Add ability to add arbitrary query string params for lnurl pays
  lnurl-test/src/test/scala/org/bitcoins/lnurl/LnURLClientTest.scala
  lnurl/src/main/scala/org/bitcoins/lnurl/LnURLClient.scala
Labels: enhancement, lnurl

#4997 Improve Inventory toString messages
  core/src/main/scala/org/bitcoins/core/p2p/Inventory.scala
  core/src/main/scala/org/bitcoins/core/p2p/NetworkPayload.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
Labels: enhancement, core

#5002 Add db mapper for ECDigitalSignature
  db-commons/src/main/scala/org/bitcoins/db/DbCommonsColumnMappers.scala
Labels: db-commons

#5003 Check compact filter headers if we have already stored them in the database
  chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala
  chain/src/main/scala/org/bitcoins/chain/models/CompactFilterHeaderDAO.scala
Labels: bug, chain

#5004 Update scodec-bits to 1.1.36
  project/Deps.scala
Labels: dependencies

#5001 Update sqlite-jdbc to 3.41.0.0
  project/Deps.scala
Labels: dependencies

#4998 Update sbt-native-packager to 1.9.16
  project/plugins.sbt
Labels: dependencies
