Repository bitcoin-s/bitcoin-s, pull requests merged in 2024-09, with the labels that each got.

#5654 core: Fix bug in `RescanStarted.entireRescanDoneF`
  core/src/main/scala/org/bitcoins/core/wallet/rescan/RescanState.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/RescanHandlingTest.scala
Labels: bug, core

#5653 Update ant to 1.10.15
  project/Deps.scala
Labels: dependencies

#5657 refactor: Provide `DLCWalletUtil.verifyProperlySetTxIds()` with the contractId
  testkit/src/main/scala/org/bitcoins/testkit/wallet/DLCWalletUtil.scala
Labels: refactor, dlc-wallet

#5656 Update sbt-scoverage to 2.2.0
  project/plugins.sbt
Labels: dependencies

#5661 Make `WebsocketTests` rescan test more robust
  app-commons/src/main/scala/org/bitcoins/commons/serializers/Picklers.scala
  app/server-routes/src/main/scala/org/bitcoins/server/routes/Server.scala
  app/server-test/src/test/scala/org/bitcoins/server/BitcoinSServerMainBitcoindTest.scala
  app/server-test/src/test/scala/org/bitcoins/server/WebsocketTests.scala
  app/server/src/main/scala/org/bitcoins/server/WalletRoutes.scala
  core/src/main/scala/org/bitcoins/core/hd/HDAccount.scala
  core/src/main/scala/org/bitcoins/core/serializers/PicklerKeys.scala
  node/src/main/scala/org/bitcoins/node/callback/NodeCallbackStreamManager.scala
Labels: app server, api-breaking

#5658 Update logback-classic to 1.5.8
  project/Deps.scala
Labels: dependencies

#5660 Add payload to query timeout log
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
Labels: node

#5664 cli: Fix log output for `bitcoin-s-cli`
  app/cli/src/main/resources/logback.xml
  app/cli/src/main/scala/org/bitcoins/cli/Cli.scala
Labels: bug, cli

#5666 Add caveat for `ConnectPeer` logic to only attempt to sync from a peer when a query is timed out
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/PeerConnection.scala
Labels: node

#5667 Remove potential deadlock in `managePeerAfterInitialization()` when offering to queue
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
Labels: bug, node

#5669 Update sbt to 1.10.2
  project/build.properties
Labels: dependencies

#5670 Update scalacheck to 1.18.1
  project/Deps.scala
Labels: dependencies

#5671 Update sbt-mdoc to 2.6.0
  project/plugins.sbt
Labels: dependencies

#5668 Update jna to 5.15.0
  project/Deps.scala
Labels: dependencies

#5659 2024 08 27 transaction processing refactor
  app/server-test/src/test/scala/org/bitcoins/server/RoutesSpec.scala
  app/server/src/main/scala/org/bitcoins/server/BitcoindRpcBackendUtil.scala
  app/server/src/main/scala/org/bitcoins/server/WalletRoutes.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/RescanHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/TransactionProcessingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/UtxoHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/WalletApi.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/internal/DLCDataManagement.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/internal/DLCTransactionProcessing.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/DLCWalletUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/FundWalletUtil.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/ProcessTransactionTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/RescanHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletCallbackTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/WalletHolder.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/RescanHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/TransactionProcessing.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/UtxoHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/sync/WalletSync.scala
Labels: wallet, refactor, api-breaking, dlc-wallet

#5673 Update sbt-bloop to 2.0.1
  project/plugins.sbt
Labels: dependencies

#5674 Update sbt-mdoc to 2.6.1
  project/plugins.sbt
Labels: dependencies

#5675 Refactor codebase to have has-a relationship with `RescanHandling` rather than is-a
  app/server-test/src/test/scala/org/bitcoins/server/RoutesSpec.scala
  app/server/src/main/scala/org/bitcoins/server/DLCWalletLoaderApi.scala
  app/server/src/main/scala/org/bitcoins/server/WalletRoutes.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/AccountHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/HDWalletApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/NeutrinoWalletApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/RescanHandlingApi.scala
  dlc-wallet-test/src/test/scala/org/bitcoins/dlc/wallet/RescanDLCTest.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCAppConfig.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/internal/DLCTransactionProcessing.scala
  docs/wallet/wallet-rescan.md
  docs/wallet/wallet.md
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeWithWalletTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/BitcoinSWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/RescanHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/TrezorAddressTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletUnitTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/WalletHolder.scala
  wallet/src/main/scala/org/bitcoins/wallet/config/WalletAppConfig.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/AccountHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/RescanHandling.scala
Labels: wallet, refactor, api-breaking

#5679 2024 09 19 address handling refactor
  app/server-routes/src/main/scala/org/bitcoins/server/routes/ServerRoute.scala
  app/server-test/src/test/scala/org/bitcoins/server/CallBackUtilTest.scala
  app/server-test/src/test/scala/org/bitcoins/server/RoutesSpec.scala
  app/server-test/src/test/scala/org/bitcoins/server/WalletRoutesSpec.scala
  app/server-test/src/test/scala/org/bitcoins/wallet/MockWalletApi.scala
  app/server/src/main/scala/org/bitcoins/server/WalletRoutes.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/AccountHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/AddressHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/HDWalletApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/WalletApi.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeWithWalletTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/BitcoinSWalletTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/FundWalletUtil.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/AddressHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/AddressLabelTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/AddressTagIntegrationTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/FundTransactionHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/LegacyWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/ProcessBlockTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/RescanHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/SegwitWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/TrezorAddressTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletCallbackTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletUnitTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/WalletHolder.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/AccountHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/AddressHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/FundTransactionHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/RescanHandling.scala
Labels: wallet, refactor, api-breaking

#5677 Update sbt-bloop to 2.0.2
  project/plugins.sbt
Labels: dependencies

#5680 Add `SendFundsHandlingApi`, remove `HDWalletApi`
  app/server-test/src/test/scala/org/bitcoins/server/DLCRoutesSpec.scala
  app/server-test/src/test/scala/org/bitcoins/server/RoutesSpec.scala
  app/server-test/src/test/scala/org/bitcoins/server/WalletRoutesSpec.scala
  app/server-test/src/test/scala/org/bitcoins/wallet/MockWalletApi.scala
  app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala
  app/server/src/main/scala/org/bitcoins/server/BitcoindRpcBackendUtil.scala
  app/server/src/main/scala/org/bitcoins/server/WalletRoutes.scala
  app/server/src/main/scala/org/bitcoins/server/util/CallbackUtil.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/AccountHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/SendFundsHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/UtxoHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/WalletApi.scala
  dlc-wallet-test/src/test/scala/org/bitcoins/dlc/wallet/DLCWalletCallbackTest.scala
  dlc-wallet-test/src/test/scala/org/bitcoins/dlc/wallet/MultiWalletDLCTest.scala
  dlc-wallet-test/src/test/scala/org/bitcoins/dlc/wallet/WalletDLCSetupTest.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala
  docs/wallet/wallet-callbacks.md
  docs/wallet/wallet-rescan.md
  docs/wallet/wallet.md
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeWithWalletTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/BitcoinSWalletTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/DLCWalletUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/FundWalletUtil.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/AddressHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/AddressTagIntegrationTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/BitcoindBlockPollingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/FundTransactionHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/LegacyWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/MultiWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/ProcessBlockTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/ProcessTransactionTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/RescanHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/SegwitWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/TrezorAddressTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/UTXOLifeCycleTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletCallbackTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletIntegrationTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletSendingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletUnitTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/WalletHolder.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/AccountHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/FundTransactionHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/SendFundsHandlingHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/UtxoHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/sync/WalletSync.scala
Labels: wallet, refactor, api-breaking

#5684 Move `RandomFeeProvider` to src
  fee-provider/src/main/scala/org/bitcoins/feeprovider/FeeProviderFactory.scala
  fee-provider/src/main/scala/org/bitcoins/feeprovider/FeeProviderName.scala
  fee-provider/src/main/scala/org/bitcoins/feeprovider/RandomFeeProvider.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/BitcoinSWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletIntegrationTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletSendingTest.scala
Labels: fee-provider

#5683 Update junixsocket-core to 2.10.1
  project/Deps.scala
Labels: dependencies

#5682 Update waffle-jna to 3.5.0
  project/Deps.scala
Labels: dependencies

#5688 Update sqlite-jdbc to 3.46.1.3
  project/Deps.scala
Labels: dependencies

#5681 refactor: Move more methods out of `WalletApi`
  app/server-test/src/test/scala/org/bitcoins/server/RoutesSpec.scala
  app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala
  app/server/src/main/scala/org/bitcoins/server/BitcoindRpcBackendUtil.scala
  app/server/src/main/scala/org/bitcoins/server/WalletRoutes.scala
  app/server/src/main/scala/org/bitcoins/server/util/CallbackUtil.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/AddressHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/SendFundsHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/TransactionProcessingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/UtxoHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/WalletApi.scala
  dlc-wallet-test/src/test/scala/org/bitcoins/dlc/wallet/MultiWalletDLCTest.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/internal/DLCTransactionProcessing.scala
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeWithWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/AddressHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/AddressTagIntegrationTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/BitcoindBackendTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/FundTransactionHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/ProcessBlockTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/ProcessTransactionTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/RescanHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/UTXOLifeCycleTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletCallbackTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletIntegrationTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletSendingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletUnitTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/WalletHolder.scala
  wallet/src/main/scala/org/bitcoins/wallet/config/WalletAppConfig.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/AddressHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/SendFundsHandlingHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/TransactionProcessing.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/UtxoHandling.scala
Labels: wallet, refactor

#5685 2024 09 24 simplify wallet
  app/server-test/src/test/scala/org/bitcoins/server/RoutesSpec.scala
  app/server-test/src/test/scala/org/bitcoins/server/WalletRoutesSpec.scala
  app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala
  app/server/src/main/scala/org/bitcoins/server/BitcoindRpcBackendUtil.scala
  app/server/src/main/scala/org/bitcoins/server/DLCWalletLoaderApi.scala
  build.sbt
  core/src/main/scala/org/bitcoins/core/api/wallet/WalletApi.scala
  dlc-wallet-test/src/test/scala/org/bitcoins/dlc/wallet/RescanDLCTest.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCAppConfig.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala
  docs/chain/chain-query-api.md
  docs/node/node-api.md
  docs/wallet/wallet-callbacks.md
  docs/wallet/wallet-sync.md
  docs/wallet/wallet.md
  fee-provider/src/main/scala/org/bitcoins/feeprovider/FeeProviderName.scala
  fee-provider/src/main/scala/org/bitcoins/feeprovider/RandomFeeProvider.scala
  testkit/src/main/scala/org/bitcoins/testkit/BitcoinSTestAppConfig.scala
  testkit/src/main/scala/org/bitcoins/testkit/node/NodeTestWithCachedBitcoind.scala
  testkit/src/main/scala/org/bitcoins/testkit/server/WalletLoaderFixtures.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/BitcoinSWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/TrezorAddressTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletUnitTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/WalletHolder.scala
  wallet/src/main/scala/org/bitcoins/wallet/config/WalletAppConfig.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/AccountHandling.scala
Labels: wallet, refactor

#5689 Update sbt-scalajs, scalajs-compiler, ... to 1.17.0
  project/plugins.sbt
Labels: dependencies, scalajs

#5690 Update slick, slick-hikaricp to 3.5.2
  project/Deps.scala
Labels: dependencies

#5691 Update sbt-coveralls to 1.3.14
  project/plugins.sbt
Labels: dependencies
