Repository bitcoin-s/bitcoin-s, pull requests merged in 2024-08, with the labels that each got.

#5631 2024 07 31 bitcoind callbacks
  app/server/src/main/scala/org/bitcoins/server/util/CallbackUtil.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/BitcoindInstanceTest.scala
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/WalletRpcTest.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/BitcoindCallbacks.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/BitcoindRpcClient.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/Client.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/v25/BitcoindV25RpcClient.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/v26/BitcoindV26RpcClient.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/v27/BitcoindV27RpcClient.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/config/BitcoindInstance.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/config/BitcoindRpcAppConfig.scala
  core/src/main/scala/org/bitcoins/core/api/callback/NodeApiCallbacks.scala
  docs/chain/chain-query-api.md
  docs/node/node-api.md
  docs/node/node.md
  docs/rpc/bitcoind.md
  node-test/src/test/scala/org/bitcoins/node/networking/peer/DataMessageHandlerTest.scala
  node/src/main/scala/org/bitcoins/node/NodeCallbacks.scala
  node/src/main/scala/org/bitcoins/node/callback/NodeCallbackStreamManager.scala
  testkit/src/main/scala/org/bitcoins/testkit/eclair/rpc/EclairRpcTestUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/fixtures/BitcoinSFixture.scala
  testkit/src/main/scala/org/bitcoins/testkit/rpc/BitcoindRpcTestUtil.scala
Labels: bitcoind-rpc

#5632 2024 07 29 rm tx bitcoind callbacks
  app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala
  app/server/src/main/scala/org/bitcoins/server/BitcoindRpcBackendUtil.scala
  app/server/src/main/scala/org/bitcoins/server/util/CallbackUtil.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/BitcoindRpcClient.scala
  testkit-core/.jvm/src/main/resources/logback-test.xml
  wallet-test/src/test/scala/org/bitcoins/wallet/BitcoindBlockPollingTest.scala
Labels: app server

#5634 Update sqlite-jdbc to 3.46.0.1
  project/Deps.scala
Labels: dependencies

#5633 Update sbt-native-packager to 1.10.4
  project/plugins.sbt
Labels: dependencies

#5635 Refactor `WalletApi.createNewAccount` to not use `KeyManagerParams`
  app/server/src/main/scala/org/bitcoins/server/WalletRoutes.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/HDWalletApi.scala
  testkit/src/main/scala/org/bitcoins/testkit/server/BitcoinSServerMainBitcoindFixture.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/BitcoinSWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/FundTransactionHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/TrezorAddressTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/WalletHolder.scala
Labels: wallet, refactor

#5636 Update client3:core, ... to 3.9.8
  project/Deps.scala
Labels: dependencies

#5638 2024 08 07 `createnewaccount` rpc
  app-commons/src/main/scala/org/bitcoins/commons/rpc/Command.scala
  app-commons/src/main/scala/org/bitcoins/commons/serializers/Picklers.scala
  app/cli/src/main/scala/org/bitcoins/cli/ConsoleCli.scala
  app/server-test/src/test/scala/org/bitcoins/server/RoutesSpec.scala
  app/server-test/src/test/scala/org/bitcoins/server/WalletRoutesSpec.scala
  app/server/src/main/scala/org/bitcoins/server/WalletRoutes.scala
  build.sbt
  core-test/src/test/scala/org/bitcoins/core/crypto/bip32/BIP32PathTest.scala
  core-test/src/test/scala/org/bitcoins/core/hd/HDPathTest.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/db/AddressRecord.scala
  core/src/main/scala/org/bitcoins/core/crypto/ExtKeyVersion.scala
  core/src/main/scala/org/bitcoins/core/hd/BIP32Path.scala
  core/src/main/scala/org/bitcoins/core/hd/HDAccount.scala
  core/src/main/scala/org/bitcoins/core/hd/HDAddress.scala
  core/src/main/scala/org/bitcoins/core/hd/HDCoin.scala
  core/src/main/scala/org/bitcoins/core/hd/HDPathFactory.scala
  core/src/main/scala/org/bitcoins/core/hd/HDPurpose.scala
  core/src/main/scala/org/bitcoins/core/util/HDUtil.scala
  db-commons/src/main/scala/org/bitcoins/db/DbCommonsColumnMappers.scala
  dlc-oracle/src/main/scala/org/bitcoins/dlc/oracle/DLCOracle.scala
  docs/applications/server.md
  docs/key-manager/key-manager.md
  key-manager-test/src/test/scala/org/bitcoins/keymanager/bip39/BIP39KeyManagerApiTest.scala
  key-manager-test/src/test/scala/org/bitcoins/keymanager/util/HdUtilTest.scala
  key-manager/src/main/scala/org/bitcoins/keymanager/config/KeyManagerAppConfig.scala
  testkit-core/src/main/scala/org/bitcoins/testkitcore/gen/HDGenerators.scala
  testkit-core/src/main/scala/org/bitcoins/testkitcore/wallet/WalletTestUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/keymanager/KeyManagerTestUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/WalletTestUtil.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/LegacyWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/SegwitWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/TrezorAddressTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletAppConfigTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/util/GetAddresses.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/config/WalletAppConfig.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/AccountHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/AddressHandling.scala
Labels: wallet, cli, app server, api-breaking

#5640 refactor: Change interval param of `BitcoindRpcBackendUtil.startBitcoindBlockPolling`
  app/server/src/main/scala/org/bitcoins/server/BitcoindRpcBackendUtil.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/BitcoindBlockPollingTest.scala
Labels: refactor, app server

#5641 Update sbt-ci-release to 1.6.0
  project/plugins.sbt
Labels: dependencies

#5637 Update slf4j-api to 2.0.16
  project/Deps.scala
Labels: dependencies

#5642 Update sbt-bloop to 2.0.0
  project/plugins.sbt
Labels: dependencies

#5639 2024 08 13 walletholder appserver refactor
  app/server-test/src/test/scala/org/bitcoins/server/WebsocketTests.scala
  app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala
  testkit/src/main/scala/org/bitcoins/testkit/server/BitcoinSServerMainBitcoindFixture.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/FundWalletUtil.scala
Labels: refactor, app server

#5646 Update sqlite-jdbc to 3.46.1.0
  project/Deps.scala
Labels: dependencies

#5643 Update logback-classic to 1.5.7
  project/Deps.scala
Labels: dependencies

#5627 Create `AccountHandlingApi`, move inheritance from `Wallet` into `HDWalletApi`
  app/server-test/src/test/scala/org/bitcoins/server/RoutesSpec.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/AccountHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/HDWalletApi.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/WalletHolder.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/AccountHandling.scala
Labels: wallet, refactor

#5647 Update sbt-ci-release to 1.6.1
  project/plugins.sbt
Labels: dependencies

#5644 Update metrics-core, metrics-healthchecks, ... to 4.2.27
  project/Deps.scala
Labels: dependencies

#5650 wallet: Remove unecessary type parameter to `TxCRUDComponent#TxTable`
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/models/DLCRemoteTxDAO.scala
  wallet/src/main/scala/org/bitcoins/wallet/models/IncomingTransactionDAO.scala
  wallet/src/main/scala/org/bitcoins/wallet/models/OutgoingTransactionDAO.scala
  wallet/src/main/scala/org/bitcoins/wallet/models/TransactionDAO.scala
Labels: wallet, refactor

#5649 Update sbt-scoverage to 2.1.1
  project/plugins.sbt
Labels: dependencies

#5651 Add `FundTransactionHandlingApi`, make `FundTransactionHandling` a case class
  core/src/main/scala/org/bitcoins/core/api/wallet/FundTransactionHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/HDWalletApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/WalletApi.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/AddressTagIntegrationTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/FundTransactionHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/ProcessTransactionTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/UTXOLifeCycleTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/WalletHolder.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/FundTransactionHandling.scala
Labels: wallet, refactor

#5648 Update postgresql to 42.7.4
  project/Deps.scala
Labels: dependencies

#5652 Move `DLCDAOs` to `src/`
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/models/DLCDAOs.scala
  testkit/src/main/scala/org/bitcoins/testkit/fixtures/DLCDAOFixture.scala
Labels: refactor, dlc-wallet
