Repository bitcoin-s/bitcoin-s, pull requests merged in 2024-12, with the labels that each got.

#5798 Update sbt, scripted-plugin to 1.10.6
  project/build.properties
Labels: dependencies

#5799 Update flyway-core, ... to 11.0.1
  project/Deps.scala
Labels: dependencies

#5800 Add `NodeState.NoPeers`, cache network messages
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeWithWalletTest.scala
  node/src/main/scala/org/bitcoins/node/NeutrinoNode.scala
  node/src/main/scala/org/bitcoins/node/NodeState.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
Labels: enhancement, node

#5803 2024 12 11 issue 5625
  core/src/main/scala/org/bitcoins/core/api/wallet/UtxoHandlingApi.scala
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeWithWalletTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/UtxoHandling.scala
Labels: wallet

#5808 Update flyway-core, ... to 11.1.0
  project/Deps.scala
Labels: dependencies

#5810 chain: Add invariant that we have at least 1 header in Blockchain
  chain/src/main/scala/org/bitcoins/chain/blockchain/BaseBlockChain.scala
  chain/src/main/scala/org/bitcoins/chain/blockchain/Blockchain.scala
  chain/src/main/scala/org/bitcoins/chain/models/BlockHeaderDAO.scala
Labels: chain

#5813 Update sbt-bloop to 2.0.6
  project/plugins.sbt
Labels: dependencies

#5814 Update guava to 33.4.0-jre
  project/Deps.scala
Labels: dependencies

#5815 server: Deduplicate wrapping callbacks in streams
  app/server/src/main/scala/org/bitcoins/server/util/CallbackUtil.scala
Labels: app server

#5817 Update sbt-ci-release to 1.9.2
  project/plugins.sbt
Labels: dependencies

#5818 Update logback-classic to 1.5.14
  project/Deps.scala
Labels: dependencies

#5820 wallet: Reduce noisy DEBUG log
  wallet/src/main/scala/org/bitcoins/wallet/internal/UtxoHandling.scala
Labels: wallet

#5819 node: Move killswitch downstream to avoid queue deadlocks
  node/src/main/scala/org/bitcoins/node/networking/peer/PeerConnection.scala
  tor/src/main/scala/org/bitcoins/tor/Socks5Connection.scala
Labels: bug, node

#5821 Update logback-classic to 1.5.15
  project/Deps.scala
Labels: dependencies

#5822 Update jna to 5.16.0
  project/Deps.scala
Labels: dependencies

#5825 wallet: Refactor AddressHandling to be account specific
  core/src/main/scala/org/bitcoins/core/hd/AddressType.scala
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeWithWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/AddressHandlingTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/AccountHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/AddressHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/models/AddressDAO.scala
Labels: wallet, refactor

#5827 Update client3:core, ... to 3.10.2
  project/Deps.scala
Labels: dependencies

#5826 chore: remove redundant words in comment
  chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala
  website/versioned_docs/version-0.2.0/applications/cli.md
  website/versioned_docs/version-0.4.0/applications/cli.md
  website/versioned_docs/version-0.5.0/applications/cli.md
  website/versioned_docs/version-1.9.1/applications/cli.md
  website/versioned_docs/version-1.9.2/applications/cli.md
Labels: documentation
