Repository bitcoin-s/bitcoin-s, pull requests merged in 2024-07, with the labels that each got.

#5614 Update sbt-scoverage to 2.1.0
  project/plugins.sbt
Labels: dependencies

#5619 Update sbt-mdoc to 2.5.4
  project/plugins.sbt
Labels: dependencies

#5618 Update sbt to 1.10.1
  project/build.properties
Labels: dependencies

#5616 Update sbt-bloop to 1.6.0
  project/plugins.sbt
Labels: dependencies

#5617 Update junixsocket-core to 2.10.0
  project/Deps.scala
Labels: dependencies

#5620 Update sbt-coveralls to 1.3.12
  project/plugins.sbt
Labels: dependencies

#5623 Rework `NativeProcessFactory.cmd` to be `Vector[String]`
  app-commons/src/main/scala/org/bitcoins/commons/util/NativeProcessFactory.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/Client.scala
  clightning-rpc/src/main/scala/com/bitcoins/clightning/rpc/CLightningRpcClient.scala
  eclair-rpc/src/main/scala/org/bitcoins/eclair/rpc/client/EclairRpcClient.scala
  lnd-rpc/src/main/scala/org/bitcoins/lnd/rpc/LndRpcClient.scala
  tor/src/main/scala/org/bitcoins/tor/client/TorClient.scala
Labels: refactor, app-commons

#5624 refactor: Create `UtxoHandlingApi`, move to has-a relationship within Wallet
  core/src/main/scala/org/bitcoins/core/api/wallet/HDWalletApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/UtxoHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/WalletApi.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/FundTransactionHandlingTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/WalletHolder.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/FundTransactionHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/TransactionProcessing.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/UtxoHandling.scala
Labels: wallet, refactor, dlc-wallet

#5626 Move `WalletDAOs` to `src`
  testkit/src/main/scala/org/bitcoins/testkit/fixtures/WalletDAOFixture.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/WalletTestUtil.scala
  wallet/src/main/scala/org/bitcoins/wallet/models/WalletDAOs.scala
Labels: wallet, refactor

#5628 Remove `WalletHolder` parameter from `DLCWalletLoaderApi.loadWallet()`
  app/server/src/main/scala/org/bitcoins/server/DLCWalletLoaderApi.scala
Labels: refactor, app server

#5630 Update sbt-coveralls to 1.3.13
  project/plugins.sbt
Labels: dependencies
