Repository bitcoin-s/bitcoin-s, pull requests merged in 2025-10, with the labels that each got.

#6088 node: Add invalid block header error message to log
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
  testkit-core/.jvm/src/main/resources/logback-test.xml
Labels: node

#6092 Update jna to 5.18.1
  project/Deps.scala
Labels: dependencies

#6091 Update sbt-native-packager to 1.11.4
  project/plugins.sbt
Labels: dependencies

#6096 node: Add logs to indicate what peer a message originated from
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
Labels: node

#6098 Update sbt, scripted-plugin to 1.11.7
  project/build.properties
Labels: dependencies

#6101 ci: Update CI runners to java 25
  .github/workflows/Compile.yml
  .github/workflows/Linux_2.13_App_Chain_Core_Tests.yml
  .github/workflows/Linux_2.13_KeyManager_Wallet_DLC_Tests.yml
  .github/workflows/Linux_2.13_Node_Tests.yml
  .github/workflows/Linux_2.13_RPC_Tests.yml
  .github/workflows/Mac_2.13_Crypto_Core_AppServer_Tests.yml
  .github/workflows/Mac_2.13_RPC_Tests.yml
  .github/workflows/Mac_2.13_Wallet_Node_DLC_Tests.yml
  .github/workflows/PostgresTests.yml
  .github/workflows/Windows.yml
  .github/workflows/docker-publish.yml
  .github/workflows/release.yml
Labels: CI

#6094 Update sbt-bloop to 2.0.16
  project/plugins.sbt
Labels: dependencies
