Repository bitcoin-s/bitcoin-s, pull requests merged in 2025-09, with the labels that each got.

#6057 Update metrics-core to 5.0.4
  project/Deps.scala
Labels: dependencies

#6064 Implement `OP_CHECKSIGFROMSTACK`
  core-test/src/test/scala/org/bitcoins/core/protocol/transaction/TransactionTest.scala
  core/src/main/scala/org/bitcoins/core/script/crypto/CryptoInterpreter.scala
  core/src/main/scala/org/bitcoins/core/script/crypto/CryptoOperations.scala
  core/src/main/scala/org/bitcoins/core/script/flag/ScriptFlagFactory.scala
  core/src/main/scala/org/bitcoins/core/script/flag/ScriptFlags.scala
  core/src/main/scala/org/bitcoins/core/script/interpreter/ScriptInterpreter.scala
  core/src/main/scala/org/bitcoins/core/script/reserved/ReservedOperations.scala
Labels: core, POC

#6066 Revert "Implement `OP_CHECKSIGFROMSTACK`"
  core-test/src/test/scala/org/bitcoins/core/protocol/transaction/TransactionTest.scala
  core/src/main/scala/org/bitcoins/core/script/crypto/CryptoInterpreter.scala
  core/src/main/scala/org/bitcoins/core/script/crypto/CryptoOperations.scala
  core/src/main/scala/org/bitcoins/core/script/flag/ScriptFlagFactory.scala
  core/src/main/scala/org/bitcoins/core/script/flag/ScriptFlags.scala
  core/src/main/scala/org/bitcoins/core/script/interpreter/ScriptInterpreter.scala
  core/src/main/scala/org/bitcoins/core/script/reserved/ReservedOperations.scala
Labels: core

#6068 2025 09 10 pull scala3 files from #5713
  app/scripts/src/main/scala/org/bitcoins/scripts/CheckP2SH.scala
  app/scripts/src/main/scala/org/bitcoins/scripts/CheckP2SHDb.scala
  app/server-routes/src/main/scala/de/heikoseeberger/akkahttpupickle/UpickleSupport.scala
  app/server-routes/src/main/scala/org/bitcoins/server/routes/Server.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/config/BitcoindInstance.scala
  db-commons/src/main/scala/org/bitcoins/db/CRUD.scala
  db-commons/src/main/scala/org/bitcoins/db/CRUDAction.scala
  db-commons/src/main/scala/org/bitcoins/db/CRUDAutoInc.scala
  db-commons/src/main/scala/org/bitcoins/db/DatabaseDriver.scala
  db-commons/src/main/scala/org/bitcoins/db/DatadirUtil.scala
  db-commons/src/main/scala/org/bitcoins/db/DbAppConfig.scala
  db-commons/src/main/scala/org/bitcoins/db/DbManagement.scala
  db-commons/src/main/scala/org/bitcoins/db/HikariLogging.scala
  db-commons/src/main/scala/org/bitcoins/db/JdbcProfileComponent.scala
  db-commons/src/main/scala/org/bitcoins/db/PostgresUtil.scala
  db-commons/src/main/scala/org/bitcoins/db/SQLiteUtil.scala
  db-commons/src/main/scala/org/bitcoins/db/SlickUtil.scala
  db-commons/src/main/scala/org/bitcoins/db/util/MasterXPubUtil.scala
  dlc-oracle/src/main/scala/org/bitcoins/dlc/oracle/config/DLCOracleAppConfig.scala
  dlc-oracle/src/main/scala/org/bitcoins/dlc/oracle/util/EventDbUtil.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCDbManagement.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/internal/DLCDataManagement.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/internal/DLCTransactionProcessing.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/util/DLCActionBuilder.scala
  node/src/main/scala/org/bitcoins/node/NeutrinoNode.scala
  node/src/main/scala/org/bitcoins/node/PeerData.scala
  node/src/main/scala/org/bitcoins/node/PeerFinder.scala
  node/src/main/scala/org/bitcoins/node/db/NodeDbManagement.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/PeerConnection.scala
  node/src/main/scala/org/bitcoins/node/util/BitcoinSNodeUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/chain/ChainUnitTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/chain/fixture/ChainWithBitcoindUnitTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/node/CachedAppConfig.scala
  testkit/src/main/scala/org/bitcoins/testkit/node/NodeTestWithCachedBitcoind.scala
  testkit/src/main/scala/org/bitcoins/testkit/rpc/BitcoindFixtures.scala
  testkit/src/main/scala/org/bitcoins/testkit/rpc/CachedBitcoind.scala
  testkit/src/main/scala/org/bitcoins/testkit/tor/CachedTor.scala
  testkit/src/main/scala/org/bitcoins/testkit/util/FileUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/BaseWalletTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/BitcoinSWalletTest.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/BitcoinSWalletTestCachedBitcoind.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/DualDLCWalletTestCachedBitcoind.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/FundWalletUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/wallet/WalletAppConfigWithBitcoindFixtures.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/config/WalletAppConfig.scala
  wallet/src/main/scala/org/bitcoins/wallet/db/WalletDbManagement.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/AccountHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/FundTransactionHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/TransactionProcessing.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/UtxoHandling.scala
Labels: scala

#6020 Update sbt-scalafmt to 2.5.5
  project/plugins.sbt
Labels: dependencies

#6075 node: Add invariant to NodeState that says you cannot both be a steady state peer and be waiting for disconnection
  node/src/main/scala/org/bitcoins/node/NodeState.scala
Labels: node

#6076 Fix bug with `NodeState.removePeers()` when we are in `MisbehavingPeer` state
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeTest.scala
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeWithUncachedBitcoindTest.scala
  node/src/main/scala/org/bitcoins/node/NodeState.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
Labels: bug, node

#6077 Update metrics-core, metrics-healthchecks, ... to 4.2.37
  project/Deps.scala
Labels: dependencies

#6079 Update bcprov-jdk18on to 1.82
  project/Deps.scala
Labels: dependencies

#6083 core: Fix `CompactFilterHeaderDb.toString()`
  core/src/main/scala/org/bitcoins/core/api/chain/db/CompactFilterHeaderDb.scala
Labels: bug, core

#6081 Update guava to 33.5.0-jre
  project/Deps.scala
Labels: dependencies

#6084 Update sbt-bloop to 2.0.14
  project/plugins.sbt
Labels: dependencies

#6085 Update jna to 5.18.0
  project/Deps.scala
Labels: dependencies

#6086 Update pekko-actor, pekko-discovery, ... to 1.2.1
  project/Deps.scala
Labels: dependencies
