Repository bitcoin-s/bitcoin-s, pull requests merged in 2025-08, with the labels that each got.

#6034 Update sbt-bloop to 2.0.12
  project/plugins.sbt
Labels: dependencies

#6036 Update sbt, scripted-plugin to 1.11.4
  project/build.properties
Labels: dependencies

#6038 bitcoindRpc: Fix `listUnspent()` for `Vector[BitcoinAddress]` param
  bitcoind-rpc-test/src/test/scala/org/bitcoins/rpc/common/UTXORpcTest.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/UTXORpc.scala
Labels: bug, bitcoind-rpc

#6039 Update sbt-bloop to 2.0.13
  project/plugins.sbt
Labels: dependencies

#6040 Update scalamock to 7.4.1
  project/Deps.scala
Labels: dependencies

#5622 Add migration code to put app data in proper spot on mac for fresh installs
  .github/workflows/Mac_2.13_RPC_Tests.yml
  app-commons/src/main/scala/org/bitcoins/commons/config/AppConfig.scala
  bitcoind-rpc/bitcoind-rpc.sbt
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/Client.scala
  clightning-rpc/clightning-rpc.sbt
  core/src/main/scala/org/bitcoins/core/util/EnvUtil.scala
  eclair-rpc/eclair-rpc.sbt
  eclair-rpc/src/main/scala/org/bitcoins/eclair/rpc/client/EclairRpcClient.scala
  lnd-rpc/lnd-rpc.sbt
  project/CommonSettings.scala
  project/EnvUtil.scala
  testkit/src/main/scala/org/bitcoins/testkit/util/TestkitBinaries.scala
Labels: config, app-commons, macosx

#6045 docs: Update website deps
  website/yarn.lock
Labels: documentation

#6049 Update sbt-native-packager to 1.11.3
  project/plugins.sbt
Labels: dependencies

#6050 Update sbt-unidoc to 0.6.0
  project/plugins.sbt
Labels: dependencies

#6051 Update scalapb-runtime to 0.11.20
  project/Deps.scala
Labels: dependencies

#6052 Update metrics-core, metrics-healthchecks, ... to 4.2.34
  project/Deps.scala
Labels: dependencies

#6053 Update sbt, scripted-plugin to 1.11.5
  project/build.properties
Labels: dependencies
