Repository bitcoin-s/bitcoin-s, pull requests merged in 2025-04, with the labels that each got.

#5971 Update guava to 33.4.6-jre
  project/Deps.scala
Labels: dependencies

#5976 Update flyway-core, ... to 11.6.0
  project/Deps.scala
Labels: dependencies

#5975 Update guava to 33.4.7-jre
  project/Deps.scala
Labels: dependencies

#5980 Update gson to 2.13.0
  project/Deps.scala
Labels: dependencies

#5978 Update flyway-core, ... to 11.7.0
  project/Deps.scala
Labels: dependencies

#5977 Update client3:core, ... to 3.11.0
  project/Deps.scala
Labels: dependencies

#5979 Update sbt-mdoc to 2.7.0
  project/plugins.sbt
Labels: dependencies

#5981 Rework `ScanBitcoind` to take a `Sink` to send data to
  app/scripts/src/main/scala/org/bitcoins/scripts/CheckHASH256.scala
  app/scripts/src/main/scala/org/bitcoins/scripts/CheckP2SH.scala
  app/scripts/src/main/scala/org/bitcoins/scripts/CheckP2SHDb.scala
  app/scripts/src/main/scala/org/bitcoins/scripts/Combo.scala
  app/scripts/src/main/scala/org/bitcoins/scripts/GenP2SH.scala
  app/scripts/src/main/scala/org/bitcoins/scripts/ReadNegativeNumberResult.scala
  app/scripts/src/main/scala/org/bitcoins/scripts/ScanBitcoind.scala
Labels: scripts

#5985 Update flyway-core, ... to 11.7.2
  project/Deps.scala
Labels: dependencies

#5987 Update sbt-scalajs, scalajs-compiler, ... to 1.19.0
  project/plugins.sbt
Labels: dependencies

#5986 Update scalamock to 7.3.1
  project/Deps.scala
Labels: dependencies

#5984 Update sbt-mdoc to 2.7.1
  project/plugins.sbt
Labels: dependencies

#5989 Update flyway-core, ... to 11.8.0
  project/Deps.scala
Labels: dependencies

#5990 Fix typos and spelling errors in documentation
  website/versioned_docs/version-0.6.0/node/node.md
  website/versioned_docs/version-0.6.0/oracle-explorer-client/oracle-explorer-client.md
  website/versioned_docs/version-0.6.0/secp256k1/secp256k1.md
  website/versioned_docs/version-0.6.0/wallet/wallet-rescan.md
Labels: documentation

#5988 Update gson to 2.13.1
  project/Deps.scala
Labels: dependencies

#5983 Update guava to 33.4.8-jre
  project/Deps.scala
Labels: dependencies
