Repository bitcoin-s/bitcoin-s, pull requests merged in 2025-03, with the labels that each got.

#5947 node: Log receiving control messages
  node/src/main/scala/org/bitcoins/node/networking/peer/ControlMessageHandler.scala
Labels: node

#5951 core: Fix type annotation on `TapscriptControlBlock.apply()`
  core-test/src/test/scala/org/bitcoins/core/protocol/script/TaprootWitnessTest.scala
  core/src/main/scala/org/bitcoins/core/protocol/script/ControlBlock.scala
Labels: bug, core

#5952 core: Add ADT for `LeafVersion`
  core-test/.jvm/src/test/scala/org/bitcoins/core/protocol/transaction/TaprootWalletTestCase.scala
  core-test/src/test/scala/org/bitcoins/core/protocol/script/TaprootWitnessTest.scala
  core-test/src/test/scala/org/bitcoins/core/protocol/script/descriptor/DescriptorTest.scala
  core/src/main/scala/org/bitcoins/core/protocol/script/ControlBlock.scala
  core/src/main/scala/org/bitcoins/core/protocol/script/LeafVersion.scala
  core/src/main/scala/org/bitcoins/core/protocol/script/ScriptWitness.scala
  core/src/main/scala/org/bitcoins/core/protocol/script/TapLeaf.scala
  core/src/main/scala/org/bitcoins/core/protocol/script/descriptor/DescriptorExpression.scala
  core/src/main/scala/org/bitcoins/core/psbt/PSBTRecord.scala
  core/src/main/scala/org/bitcoins/core/script/ScriptProgram.scala
Labels: enhancement, core

#5953 core: Change type from `Byte` -> `LeafVersion` in `TapscriptControlBlock`
  core-test/src/test/scala/org/bitcoins/core/protocol/script/TaprootWitnessTest.scala
  core/src/main/scala/org/bitcoins/core/protocol/script/ControlBlock.scala
  core/src/main/scala/org/bitcoins/core/protocol/script/LeafVersion.scala
Labels: core

#5954 core: Add `TaprootWitness.sigVersion`
  core/src/main/scala/org/bitcoins/core/crypto/TxSigComponent.scala
  core/src/main/scala/org/bitcoins/core/protocol/script/ScriptWitness.scala
Labels: enhancement, core

#5955 core: Fix `TapscriptControlBlock` bugs
  core-test/src/test/scala/org/bitcoins/core/protocol/script/TaprootWitnessTest.scala
  core/src/main/scala/org/bitcoins/core/protocol/script/ControlBlock.scala
  testkit-core/src/main/scala/org/bitcoins/testkitcore/util/TransactionTestUtil.scala
Labels: bug, core

#5956 refactor: Rename `TxSigComponent.output` -> `TxSigComponent.fundingOutput`
  core-test/src/test/scala/org/bitcoins/core/crypto/TransactionSignatureSerializerTest.scala
  core/src/main/scala/org/bitcoins/core/crypto/TransactionSignatureChecker.scala
  core/src/main/scala/org/bitcoins/core/crypto/TransactionSignatureSerializer.scala
  core/src/main/scala/org/bitcoins/core/crypto/TxSigComponent.scala
  core/src/main/scala/org/bitcoins/core/protocol/dlc/verify/DLCSignatureVerifier.scala
  core/src/main/scala/org/bitcoins/core/script/interpreter/ScriptInterpreter.scala
  testkit-core/src/main/scala/org/bitcoins/testkitcore/gen/WitnessGenerators.scala
Labels: core, refactor

#5957 core: Add `TxSigComponent.spendingOutputs`
  core/src/main/scala/org/bitcoins/core/crypto/TxSigComponent.scala
Labels: core, refactor

#5960 Update flyway-core, ... to 11.4.0
  project/Deps.scala
Labels: dependencies

#5958 Update sbt-ci-release to 1.9.3
  project/plugins.sbt
Labels: dependencies

#5961 2025 03 15 Remove `data.length == 32` requirement from secp256k1jni
  secp256k1jni/src/main/java/org/bitcoin/NativeSecp256k1.java
Labels: secp256k1, crypto

#5959 Update slick, slick-hikaricp to 3.6.0
  project/Deps.scala
Labels: dependencies

#5962 node: Fix bug where we were circumventing `bitcoin-s.node.enable-peer-discovery`
  node/src/main/scala/org/bitcoins/node/PeerFinder.scala
Labels: bug, node

#5966 Update sbt-mdoc to 2.6.5
  project/plugins.sbt
Labels: dependencies

#5963 Update metrics-core to 5.0.0
  project/Deps.scala
Labels: dependencies

#5965 Update sbt, scripted-plugin to 1.10.11
  project/build.properties
Labels: dependencies

#5970 Update flyway-core, ... to 11.4.1
  project/Deps.scala
Labels: dependencies

#5964 Update jna to 5.17.0
  project/Deps.scala
Labels: dependencies

#5969 Update guava to 33.4.5-jre
  project/Deps.scala
Labels: dependencies

#5968 Update sbt-bloop to 2.0.9
  project/plugins.sbt
Labels: dependencies

#5967 Update logback-classic to 1.5.18
  project/Deps.scala
Labels: dependencies

#5945 core: Add support for testnet4
  app-commons/src/main/scala/org/bitcoins/commons/config/AppConfig.scala
  app-commons/src/main/scala/org/bitcoins/commons/jsonmodels/ExplorerEnv.scala
  app-commons/src/main/scala/org/bitcoins/commons/util/DatadirUtil.scala
  app/server/src/main/scala/org/bitcoins/server/BitcoindRpcBackendUtil.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/Client.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/config/BitcoindAuthCredentials.scala
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/config/BitcoindConfig.scala
  chain/src/main/scala/org/bitcoins/chain/pow/Pow.scala
  clightning-rpc/src/main/scala/com/bitcoins/clightning/rpc/config/CLightningConfig.scala
  clightning-rpc/src/main/scala/com/bitcoins/clightning/rpc/config/CLightningInstanceLocal.scala
  core-test/src/test/scala/org/bitcoins/core/crypto/WIFEncodingTest.scala
  core/src/main/scala/org/bitcoins/core/config/NetworkParameters.scala
  core/src/main/scala/org/bitcoins/core/hd/HDCoinType.scala
  core/src/main/scala/org/bitcoins/core/protocol/BtcHumanReadablePart.scala
  core/src/main/scala/org/bitcoins/core/protocol/blockchain/ChainParams.scala
  core/src/main/scala/org/bitcoins/core/protocol/ln/LnParams.scala
  core/src/main/scala/org/bitcoins/core/util/HDUtil.scala
  dlc-oracle/src/main/scala/org/bitcoins/dlc/oracle/config/DLCOracleAppConfig.scala
  esplora/src/main/scala/org/bitcoins/esplora/EsploraSite.scala
  fee-provider/src/main/scala/org/bitcoins/feeprovider/MempoolSpaceProvider.scala
  lnd-rpc/src/main/scala/org/bitcoins/lnd/rpc/config/LndInstance.scala
  node/src/main/scala/org/bitcoins/node/PeerFinder.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/AccountHandling.scala
Labels: enhancement, core

#5972 Update flyway-core, ... to 11.5.0
  project/Deps.scala
Labels: dependencies

#5973 Update scalamock to 7.3.0
  project/Deps.scala
Labels: dependencies
