Repository bitcoin-s/bitcoin-s, pull requests merged in 2025-01, with the labels that each got.

#5829 tests: Cleanup `BitcoindBlockPollingTest` producing ERROR logs during test fixture destruction
  wallet-test/src/test/scala/org/bitcoins/wallet/BitcoindBlockPollingTest.scala
Labels: tests

#5828 wallet: Refactor {`UTXOHandlingApi`,`AccountHandlingApi`,`AddressHandlingApi`} method names
  app/cli/src/main/scala/org/bitcoins/cli/ConsoleCli.scala
  app/server-test/src/test/scala/org/bitcoins/server/RoutesSpec.scala
  app/server-test/src/test/scala/org/bitcoins/server/WalletRoutesSpec.scala
  app/server/src/main/scala/org/bitcoins/server/WalletRoutes.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/AccountHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/AddressHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/SendFundsHandlingApi.scala
  core/src/main/scala/org/bitcoins/core/api/wallet/UtxoHandlingApi.scala
  dlc-wallet-test/src/test/scala/org/bitcoins/dlc/wallet/MultiWalletDLCTest.scala
  dlc-wallet-test/src/test/scala/org/bitcoins/dlc/wallet/WalletDLCSetupTest.scala
  dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/internal/DLCTransactionProcessing.scala
  docs/applications/server.md
  docs/wallet/wallet-rpc.md
  node-test/src/test/scala/org/bitcoins/node/NeutrinoNodeWithWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/AddressHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/AddressTagIntegrationTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/BitcoindBackendTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/FundTransactionHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/LegacyWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/ProcessBlockTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/ProcessTransactionTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/RescanHandlingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/SegwitWalletTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/TrezorAddressTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/UTXOLifeCycleTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletCallbackTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletIntegrationTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletSendingTest.scala
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletUnitTest.scala
  wallet/src/main/scala/org/bitcoins/wallet/Wallet.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/AccountHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/AddressHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/SendFundsHandlingHandling.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/UtxoHandling.scala
Labels: wallet, refactor, api-breaking

#5830 docs: Run 'yarn upgrade'
  website/yarn.lock
Labels: documentation

#5833 Update scalamock to 6.1.1
  project/Deps.scala
Labels: dependencies

#5832 Update waffle-jna to 3.5.1
  project/Deps.scala
Labels: dependencies

#5834 refactor: Improve bitcoind wallet polling logic
  app/server/src/main/scala/org/bitcoins/server/BitcoindRpcBackendUtil.scala
  app/server/src/main/scala/org/bitcoins/server/bitcoind/BitcoindSyncState.scala
  app/server/src/main/scala/org/bitcoins/server/util/BitcoindPollingCancellabe.scala
Labels: app server

#5836 Update sqlite-jdbc to 3.47.2.0
  project/Deps.scala
Labels: dependencies

#5838 Update sbt-native-packager to 1.11.0
  project/plugins.sbt
Labels: dependencies

#5839 Update flyway-core, ... to 11.1.1
  project/Deps.scala
Labels: dependencies

#5837 Update logback-classic to 1.5.16
  project/Deps.scala
Labels: dependencies

#5843 Try pinning CI image to ubuntu 22.04 for now as a workaround until `setup-java` supports `sbt` installation
  .github/workflows/Compile.yml
  .github/workflows/Linux_2.13_App_Chain_Core_Tests.yml
  .github/workflows/Linux_2.13_KeyManager_Wallet_DLC_Tests.yml
  .github/workflows/Linux_2.13_Node_Tests.yml
  .github/workflows/Linux_2.13_RPC_Tests.yml
  .github/workflows/PostgresTests.yml
  .github/workflows/docker-publish.yml
  .github/workflows/native.yml
  .github/workflows/release.yml
Labels: CI

#5841 Update sbt-scalajs, scalajs-compiler, ... to 1.18.1
  project/plugins.sbt
Labels: dependencies

#5854 feeProvider: Ignore bitcoiner.live as site seems to be down
  fee-provider-test/src/test/scala/org/bitcoins/feeprovider/FeeRateProviderTest.scala
Labels: fee-provider

#5845 core: Rework NetworkPayload traits to use `Vector` instead of `Seq`
  core-test/src/test/scala/org/bitcoins/core/p2p/GetDataMessageTest.scala
  core-test/src/test/scala/org/bitcoins/core/p2p/GetHeadersMessageTest.scala
  core/src/main/scala/org/bitcoins/core/p2p/NetworkPayload.scala
  core/src/main/scala/org/bitcoins/core/serializers/p2p/messages/RawGetBlocksMessageSerializer.scala
  core/src/main/scala/org/bitcoins/core/serializers/p2p/messages/RawGetHeadersMessageSerializer.scala
  core/src/main/scala/org/bitcoins/core/serializers/p2p/messages/RawInventoryMessageSerializer.scala
  node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala
  testkit-core/src/main/scala/org/bitcoins/testkitcore/gen/p2p/DataMessageGenerator.scala
Labels: core, api-breaking

#5853 node: Fix bug where we were dropping cached outbound messages on the floor
  app/server/src/main/resources/logback.xml
  node-test/src/test/scala/org/bitcoins/node/PeerManagerTest.scala
  node/src/main/scala/org/bitcoins/node/NodeState.scala
  node/src/main/scala/org/bitcoins/node/PeerFinder.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
Labels: bug, node

#5858 Update sbt-bloop to 2.0.7
  project/plugins.sbt
Labels: dependencies

#5859 Update metrics-core, metrics-healthchecks, ... to 4.2.30
  project/Deps.scala
Labels: dependencies

#5846 wallet: Try to avoid spurious failures on WalletSendingTest double spending test
  wallet-test/src/test/scala/org/bitcoins/wallet/WalletSendingTest.scala
Labels: wallet

#5861 Update postgresql to 42.7.5
  project/Deps.scala
Labels: dependencies

#5860 Update bcprov-jdk18on to 1.80
  project/Deps.scala
Labels: dependencies

#5863 Update sqlite-jdbc to 3.48.0.0
  project/Deps.scala
Labels: dependencies

#5862 Update scala-library to 2.13.16
  inThisBuild.sbt
  project/plugins.sbt
Labels: dependencies

#5766 Update pekko-grpc-runtime, ... to 1.1.1
  project/Deps.scala
  project/plugins.sbt
Labels: dependencies

#5809 Update sbt-mdoc to 2.6.2
  project/plugins.sbt
Labels: dependencies

#5867 node: Rename `PeerData.stop()` -> `PeerData.disconnect()`
  node/src/main/scala/org/bitcoins/node/PeerData.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
Labels: node, refactor

#5868 testkit: Make sure channel is in NORMAL state for both peers in `openAndConfirmChannel()`
  testkit/src/main/scala/org/bitcoins/testkit/eclair/rpc/EclairRpcTestUtil.scala
Labels: testkit

#5873 Update sbt-assembly to 2.3.1
  project/plugins.sbt
Labels: dependencies

#5870 Update flyway-core, ... to 11.2.0
  project/Deps.scala
Labels: dependencies

#5874 node: Use appropriate `ServiceIdentifier` throughout `node` module
  core/src/main/scala/org/bitcoins/core/p2p/ServiceIdentifier.scala
  node/src/main/scala/org/bitcoins/node/NodeState.scala
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
Labels: bug, node

#5875 node: Only query p2p seeds if we have no peers in our database
  node/src/main/scala/org/bitcoins/node/PeerFinder.scala
Labels: node, optimization

#5876 appServer: Disable tor by default
  app/server/src/main/resources/reference.conf
Labels: config, app server, tor

#5877 node: Update `hardcoded-peers.txt` with whats in `bitcoin/contrib/seeds/nodes_main.txt`
  node/src/main/resources/hardcoded-peers.txt
  node/src/main/scala/org/bitcoins/node/util/BitcoinSNodeUtil.scala
Labels: node

#5880 node: Add invariant we have peerServices when we cann `PeerManager.handleConnect()`
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
Labels: node

#5866 wallet: Batch requests for blocks during rescan
  node/src/main/scala/org/bitcoins/node/NeutrinoNode.scala
  node/src/main/scala/org/bitcoins/node/Node.scala
  wallet/src/main/scala/org/bitcoins/wallet/internal/RescanHandling.scala
Labels: bug, wallet, rescan

#5883 2025 01 23 issue 5878
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
Labels: bug, node

#5882 node: Limit initial stack push in `PeerFinder.start()` to `maxSearchCount^2`
  node/src/main/scala/org/bitcoins/node/PeerFinder.scala
Labels: node, optimization

#5885 node: Fix bug where we we could have more connections than allowed by `bitcoin-s.node.maxConnectedPeers`
  node/src/main/scala/org/bitcoins/node/PeerManager.scala
Labels: bug, node

#5886 Update sbt-scalajs, scalajs-compiler, ... to 1.18.2
  project/plugins.sbt
Labels: dependencies

#5888 Update versions to 1.9.10
  README.md
  node/src/main/scala/org/bitcoins/node/constant/NodeConstants.scala
  project/CommonSettings.scala
  website/versioned_docs/version-1.9.10/applications/server.md
  website/versioned_docs/version-1.9.10/chain/chain-query-api.md
  website/versioned_docs/version-1.9.10/chain/chain.md
  website/versioned_docs/version-1.9.10/core/adding-spks.md
  website/versioned_docs/version-1.9.10/core/addresses.md
  website/versioned_docs/version-1.9.10/core/dlc.md
  website/versioned_docs/version-1.9.10/core/hd-keys.md
  website/versioned_docs/version-1.9.10/core/psbts.md
  website/versioned_docs/version-1.9.10/core/txbuilder.md
  website/versioned_docs/version-1.9.10/crypto/adaptor-signatures.md
  website/versioned_docs/version-1.9.10/crypto/sign.md
  website/versioned_docs/version-1.9.10/getting-started.md
  website/versioned_docs/version-1.9.10/key-manager/key-manager.md
  website/versioned_docs/version-1.9.10/node/node-api.md
  website/versioned_docs/version-1.9.10/rpc/bitcoind.md
  website/versioned_docs/version-1.9.10/rpc/rpc-clients-intro.md
  website/versioned_docs/version-1.9.10/secp256k1/secp256k1.md
  website/versioned_docs/version-1.9.10/testkit/testkit.md
  website/versioned_docs/version-1.9.10/ui-setup.md
  website/versioned_docs/version-1.9.10/wallet/wallet-callbacks.md
  website/versioned_docs/version-1.9.10/wallet/wallet-sync.md
  website/versioned_docs/version-1.9.10/wallet/wallet.md
  website/versions.json
  website/yarn.lock
Labels: documentation

#5889 2025 01 09 release notes 1.9.10
  release-notes/release-notes-1.9.10.md
Labels: documentation

#5891 Update sbt-coveralls to 1.3.15
  project/plugins.sbt
Labels: dependencies

#5892 Update LICENSE
  LICENSE
Labels: documentation

#5893 Update bitcoind to 28.1/27.2
  bitcoind-rpc/bitcoind-rpc.sbt
  bitcoind-rpc/src/main/scala/org/bitcoins/rpc/client/common/BitcoindRpcClient.scala
Labels: bitcoind-rpc

#5895 lndRpc: Upgrade lnd to 0.18.4
  lnd-rpc/lnd-rpc.sbt
  lnd-rpc/src/main/scala/org/bitcoins/lnd/rpc/LndRpcClient.scala
Labels: lnd-rpc

#5894 Upgrade eclair to 0.11.0
  core/src/main/scala/org/bitcoins/core/protocol/ln/node/Feature.scala
  docs/testkit/testkit.md
  eclair-rpc-test/src/test/scala/org/bitcoins/eclair/rpc/EclairRpcClientTest.scala
  eclair-rpc/eclair-rpc.sbt
  eclair-rpc/src/main/scala/org/bitcoins/eclair/rpc/client/EclairRpcClient.scala
  lnd-rpc/lnd-rpc.sbt
  testkit/src/main/scala/org/bitcoins/testkit/eclair/rpc/EclairRpcTestUtil.scala
Labels: eclair-rpc
